Document/Testcases/0x00_OMTG-DATAST.md, Document/Testcases/0x00a_OMTG-DATAST_Android.md, README.md, attribution.md, authors_guide.md
I migrated the following test cases from the Google Doc:
OMTG-DATAST-001: Testing for Insecure Storage of Credentials and Keys 
OMTG-DATAST-002: Testing for Sensitive Data Disclosure in Log Files 
OMTG-DATAST-004: Testing for Sensitive Data Disclosure in Local Storage
OMTG-DATAST-005: Testing for Sensitive Data sent to 3rd Parties 
OMTG-DATAST-006: Test for Sensitive Data Disclosure in Process Memory
=> Added test case for OMTG-DATAST

Document/0x05d-Testing-Data-Storage.md
keys or other sensitive information = plural statement -> no 's' to 'need'
=> 0x5d - Fixed typo (removed 's')

Document/0x05d-Testing-Data-Storage.md
..when using Android 6.0 onwards. The existing paragraph was framed as if the opposite would be the case.
=> [android/backup] Auto Backup is enabled by default

Document/0x05g-Testing-Network-Communication.md, Document/0x07b-Testing-Network-Communication.md
* Fix external references – use `<sup>`.
* Fix formatting of Java code examples.
* Expand the TLS config section.
* Add example of cert pinning with okhttp.
=> TLS modern ciphers

Document/0x07a-Testing-Authentication-and-Session-Management.md
OTP bruteforce according to https://sakurity.com/otp. 
CWE links are now consistent.
=> Added OTP bruteforce + minor changes

style_guide.md
The line length is not relevant for the rendered version, we don't currently seem to enforce this rule, and it hinders editing.
Currently we have each paragraph on one line. This makes it possible to use the automatic word wrap of your favorite editor. An alternative would be to have newlines in the file to split a paragraph over multiple lines. This would make it easier to read the file in a text editor, but every time you edit the paragraph you would have to do line wrapping again.
=> Remove styleguide rule about line length

Document/0x07c-Testing-Cryptography.md
The ECB mode test was removed in commit 87a70f671782911a9124693c4b1dc0451d9ee2dc as part of the general cryptography section clean up. At the time the plan was to pare down the general section in favor of moving some content to the platform-specific chapters. However, as we were going through the clean up, we realized that the general crypto chapter should remain and performed some updates to it. Unfortunately, the ECB mode test was one of the casualties that wasn't restored.
=> Restore the ECB mode test

Document/0x03-Overview.md
On the second line of the diff, there is a typo, in "However, the fast is that",
I think you mean "the fact is".
It is just a small fix, but I'd be glad to become an  °˖✧OWASP Contributor✧˖°!
=> replace 'fast' by 'fact' in 'the fact is' sentence

Document/0x05g-Testing-Network-Communication.md
Hello,
I have added information about TLS error ignoring in the context of WebView, precisely in case of bad usage of the WebViewClient.
Thanks in advance for your feedback
=> TLS error ignoring in the context of WebView

Document/0x05g-Testing-Network-Communication.md
Hi,
I haved added an info about handling of TLS certificate by Apache Cordova if application is in debug mode.
Thanks in advance.
=> Handling of TLS certificate by Apache Cordova

Document/0x04b-Mobile-App-Security-Testing.md
Following Bernhard's request : First attempt to merge both chapters (0x04b-Mobile-App-Security-Testing & 0x04d-Security-Testing-SDLC) : took all paragraphs from 0x4d and appended them to the end of 0x4b. However, much work is left as I am planning to
- restructure chapter on SDLC (clarify, remove redundancies, make it less verbose)
- adapt structure of the new 0x4b chapter
- shorten the final 0x4b chapter
The former 0x4d chapter can be removed.
=> 0x4b - Merge general Security Testing chapter with SDLC chapter

Document/0x04e-Testing-Authentication-and-Session-Management.md
"The app will generate a public/private key pair when the user `signs` (was sigs) up, ...."
=> Fix Typo - 0x04e-Testing-Authentication-and-Session-Management

Document/0x05a-Platform-Overview.md
In the last sentence : "it forks a new process which then loads and executes `the the` app-specific code."
->  "it forks a new process which then loads and executes `the` app-specific code."
=> Fix typo in Platform Overview - Zygote Section

Document/0x05a-Platform-Overview.md
Fix typo - "The example below shows an `AndroidManifest.xml` (was AndroidManifes.xml) sample requesting permission to read SMS messages:"
Improve Sentence structure  - "Content Providers are a little bit different. They allow separate permissions for read, write or access `of` (previously not there) the Content Provider using a content URI."
=> Fix Typo, Improve Sentence Structure - 0x05a-Platform-Overview

Document/0x05c-Reverse-Engineering-and-Tampering.md
Added SDK Manager access and NDK installation steps directly from the initial Android Studio window, as well as NDK default path locations.
Fixed a couple of typos.
=> Update 0x05c-Reverse-Engineering-and-Tampering.md - Setting up the Android SDK & NDK

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
These are the changes that were required to be able to compile and
load a native library for the propposed monitor using the following
reference:
https://developer.android.com/studio/projects/add-native-code.html
=> Fix syntax for PTRACE monitor to compile with CMake.

Document/0x05c-Reverse-Engineering-and-Tampering.md
The docs shows two different commands: one to find the version and other one to download the frida-server binary after manually updating the version in the url. (As of now the latest frida version downloaded using pypi is: 10.8.2)
I added single bash command `wget https://github.com/frida/frida/releases/download/$(frida --version)/frida-server-$(frida --version)-android-arm.xz` which eases the download of the right binary in single step.
=> Added frida-server download command

Document/0x05c-Reverse-Engineering-and-Tampering.md
`OMTG-Files` directory no more exists. Also the previous URL uses `/blob/master/` which give HTML output even if the apk exists.
**Changes:**
- Changed the URL to `https://github.com/OWASP/owasp-mstg/raw/master/Samples/Android/01_HelloWorld-JNI/HelloWord-JNI.apk` so that wget downloads the apk file
=> Updated HelloWord-JNI.apk URL

Document/0x05d-Testing-Data-Storage.md
I've tried the adb command with just one argument. I failed with that so, I have found out a solution at least for my case that the abe needs more arguments to complete the unpack process as such expected tar file and optional "password" argument.
=> Added abe unpack troubleshooting

Document/0x06b-Basic-Security-Testing.md
Hello,
The PR add information to handle the case in which an application require an iPad and the auditor have only iPhone or iPod devices.
Checklist state:
Thanks you very much in advance.
=> Add information to allow application installation on a non-iPad device

Document/0x05c-Reverse-Engineering-and-Tampering.md
This pull request fixes a typo in a code section that mixed code and non-code text.
=> Fix typo in code - File hiding example in 0x05c

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
This commit adds Magisk manager package to the list of popular Android rooting tools.
=> Add Magisk manager package name to list

Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04f-Testing-Network-Communication.md, Document/0x04h-Testing-Code-Quality.md, Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05d-Testing-Data-Storage.md, Document/0x05h-Testing-Platform-Interaction.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md, Document/0x06d-Testing-Data-Storage.md, Document/0x06e-Testing-Cryptography.md, Document/0x06g-Testing-Network-Communication.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
- Added the proper language syntax to code chunks to get it properly highlighted.
- Fixed some inconsistencies in code indentation.
- Added some $ at the beginning of console commands.
There is more work pending around this. I think I will open an issue to talk about it and see if there is already a standard in this project, e.g. should all console commands start with $ to differentiate the input command from output? or max line length in code chunks...
=> Fix markdown for code chunks

Document/0x06d-Testing-Data-Storage.md
The standard Unix log file (tail -f /var/log/syslog) does not exist in several iOS versions (if any). A tool to access ASL is ondeviceconsole.
=> Change syslog access by ondeviceconsole

Document/0x06d-Testing-Data-Storage.md
To use Fridump you need to have either a jailbroken/rooted device with Frida-server installed. But there is possible guided by Frida website
=> Added method to use Fridump in no-jailbroken device

Document/0x06b-Basic-Security-Testing.md
I've been spending 2 hours to fix the error when I tried to use the modules in Needle. It shown me an error regarding the lack of command line as such lipo or apt-get command isn't available.
=> Installing needle dependencies, apt-get

Document/0x05a-Platform-Overview.md
Hello,
I think it should be Files rather than Giles.
Giles -> Files
=> Fix typo - 0x05a-Platform-Overview.md

Document/0x05e-Testing-Cryptography.md
Proposing a fix to a very small typo in a code sample in the 0x5e Testing Cryptography guide
=> Fix to small typo in code sample in 0x05e

Document/0x05d-Testing-Data-Storage.md
Instead of finding an older adb tool version, putting the argument within quotes will help  eg: $ adb backup "-apk -nosystem <package-name>"
=> Alternative command added for adb backup

Document-ja/0x08-Testing-Tools.md
=> merge 'Add RE tools to Testing Tools' into doc-ja/08-tools

Document/0x04g-Testing-Cryptography.md
Thank you all for creating such an awesome resource!
Changes:
- It some situations -> In some situations
- very difficult determine the original input -> very difficult to determine the original input
- cryptographically-secure random number generator -> cryptographically secure random number generator
- 128 bit blocks -> 128-bit blocks
=> Fixed typo and improved consistency in cryptography document

style_guide.md
* Surround the escaped markdown in a code block. Otherwise it just looks like broken markdown
* Added guidelines on parameters
=> Small fix for style guide

Document/0x06b-Basic-Security-Testing.md
In this PR, the level 1, 2, 3 and 4 are the same on iOS 0x06b and Android 0x05b.
* iOS Basic Security Testing
* iOS Testing Setup
* Host Device
* Testing Device
* Recommended Tools
* Basic Testing Operations
* Accessing the Device Shell
* Host-Device Data Transfer
* Obtaining and Extracting Apps
* Installing Apps
* Information Gathering
* Static Analysis
* Dynamic Analysis
* Setting up a Network Testing Environment
* Basic Network Monitoring/Sniffing
* Setting Up an Interception Proxy
* Potential Obstacles
* References
* Tools
* Android Basic Security Testing
* Android Testing Setup
* Host Device
* Testing Device
* Recommended Tools
* Basic Testing Operations
* Accessing the Device Shell
* Host-Device Data Transfer
* Obtaining and Extracting Apps
* Installing Apps
* Information Gathering …
=> Further aligning basic security testing for Android and iOS

Document/0x06b-Basic-Security-Testing.md
Merge conflict made it to master. Deleted the pinning, as it's already moved to network section and ssl pinning testcase
=> removed pinning section from basic testing

Document/0x05b-Basic-Security_Testing.md
Added info about extracting apps and the differences between the methods. 
This PR covers issue #1238.
=> Adds info about extracting apps. Fixes #1238

Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
This PR removes the "#### Tools" sections at the bottom of both chapters 0x5b/6b
- done after checking that are referenced before.
- some links were moved to "References" as they are not tools anyway.
- all other missing "References" were also added to these chapters.
- if we would keep this list we would have to sync it constantly as the chapter changes and if we add more recommended tools in the "Recommended tools" section. 
- the "Recommended tools" section should serve as an overview of the recommended tools.
- other tools are not part of the "Recommended tools" section but they are mentioned inline, which is sufficient I would say. In case not, I would rather include them in the "Recommended tools" section.
In addition, this PR adds the missing Tools and references in 0x5c and 0x6c …
=> Fixing tools and refs

README.md
=> Fixes #1353 - Slack Channel Link Update

Document/0x04h-Testing-Code-Quality.md
No PR. 
Jeroen found it during review and ARCH-2 should be removed from XSS.
=> removed arch-2 for xss

Document/0x04e-Testing-Authentication-and-Session-Management.md
The OWASP Authentication Cheat Sheet cited for details on checking passwords and found at https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html further refers to https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements, which explicitly states, "2.1.9 ... There should be **no** requirement for upper or lower case or numbers or special characters." (emphasis mine.)
It also does not (no longer) have a rule that forbids repeat characters.
This seems to be in line with the 2019 NIST password recommendation contained in  https://pages.nist.gov/800-63-3/sp800-63b.html
=> Remove password rules and checks that contradict the cited cheat sheet.

Document/0x04e-Testing-Authentication-and-Session-Management.md
This pull request aims to make some small changes to the token renewal example. It adjusts the example endpoint & variable names, plus the example code comments, to more clearly articulate the idea that a refresh token is being provided into the request to retrieve a fresh, short-lived access token.
=> Clarify access token renewal code example

Document/0x06d-Testing-Data-Storage.md
```- [ ] You verified/tested the effectiveness of your contribution```
👆 This part is especially funny because Needle framework is pretty abandoned and supports only iOS 8, 9 and 10 and most modules support only 32 bit devices. Rather then enhancing `Dynamic Analyse with Needle` section we'd better consider replacing it with dynamic analyse with separate tools that once were included as modules into Needle.
This PR contains only a mention that Data protection class of a file can be verified during dynamic analysis. Hope interested reader will find her way to run `FileDP` on modern devices with modern jailbreaks.
=> introduce FileDP tool for Data Protection Class verification

Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04i-Testing-user-interaction.md, Document/0x05g-Testing-Network-Communication.md, Document/0x06f-Testing-Local-Authentication.md, style_guide.md
- style guide and typo fixes for 4e
- fixed missing reference links and format
- style guide.md: fixed titles and markdown code blocks; added new referencing for web links.
=> Add Reference Web Links Format to Style Guide + Fixes

style_guide.md
We are mostly using addresses without backticks. To keep it consistent in the future, I've added it to the style guide.
=> added memory addresses to style guide

Document/0x05c-Reverse-Engineering-and-Tampering.md
Since https://github.com/iBotPeaches/Apktool/issues/1061 (2015)
Apktool no longer supports these options.
- [✔️ ] Your contribution is written in the 2nd person (e.g. you)
- [✔️ ] Your contribution is written in an active present form for as much as possible.
- [ ✔️] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ✔️] Your contribution has proper formatted markdown and/or code
- [ ✔️] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ✔️] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? …
=> Remove old instruction for APK Debugging

Document/0x04f-Testing-Network-Communication.md
Add info to set 'Support invisible proxy' in 0x04f-Testing-Network-Communication.md to section regarding bettercap.
This PR covers issue #1591.
=> Add info to set 'Support invisible proxy' in 0x04f-Testing-Network-Communication.md

PULL_REQUEST_TEMPLATE.md
Until now we were missing a nice feature of GitHub: the linking between PRs and the issues related. With this change we'll be able to map PRs the the issues they close. And the issues will be closed only if the PR is merged to master. And this will happen automatically.
=> fix linking between PRs and issues

Document/0x04f-Testing-Network-Communication.md, Document/0x05h-Testing-Platform-Interaction.md
Testing Custom Certificate Stores and Certificate Pinning (MSTG-NETWORK-4) section was referenced but the title was wrong.
Before: Some applications may not work with proxies like Burp and ZAP because of Certificate Pinning. In such a scenario, please check "Testing Custom Certificate Stores and SSL Pinning".
After: Some applications may not work with proxies like Burp and ZAP because of Certificate Pinning. In such a scenario, please check "Testing Custom Certificate Stores and Certificate Pinning".
=> Fix wrong reference title SSL->Certificate

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
need to be lowercase:
```
$ sudo gem install CocoaPods-dependencies
Password:
Sorry, try again.
Password:
ERROR:  Could not find a valid gem 'CocoaPods-dependencies' (>= 0) in any repository
ERROR:  Possible alternatives: cocoapods-dependencies
```
=> Fix cocoapods

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
There is this [list of files associated with jailbreaks](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/jailbreak-detection-methods/) from trustwave that has two additional files to check:
/var/tmp/cydia.log
/var/log/syslog
Here is more evidence regarding /var/log/syslog is related to jailbreak tools: https://www.theiphonewiki.com/wiki/System_Log#On-device_with_saving_to_a_file
I haven't found an alternative supporting evidence for the /var/tmp/cydia.log file, I'm trusting trustwave reference in this case.
Feel free to discuss, and of course I can remove this file from the commit if there isn't enough information supporting it's related to jailbreak.
=> Add two files associated with jailbreaks

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
Fixed dead links in 0x05i-Testing-Code-Quality.
This PR closes #1715.
=> Fixed dead links in 0x05i-Testing-Code-Quality.

Document/0x06b-Basic-Security-Testing.md
Added a link to "Remote Shell" section that shows a step by step guide for making iproxy run automatically in the background to make ssh over usb more convenient.
=> added iPhoneWiki link for ssh over usb

Document/0x05c-Reverse-Engineering-and-Tampering.md
* Fixed the uncrackable1's package name in frida commands. sg.vantagepoint.uncrackable1 -> owasp.mstg.uncrackable1
* Updated the frida scripts. Current version of Frida is not accepting undefined variables. (added val keyword to the front of variables)
* Decompiled the app with cfr, jeb, http://www.javadecompilers.com/ and jadx. All of them creates a code that shows onclicklistener in an inner class. It is different from the code snippet on the book. So I changed the decompiled code. 
* To be able to hook a method from an inner class (onclick method on this case) we need to decompile the app and find the innerclass name so I changed the hooked method from the callback to enclosing method 'a'.
=> updated frida solution for uncrackable1

Document/0x05b-Basic-Security_Testing.md
Change old link referencing "SDK tools" from "https://developer.android.com/studio/index.html%23downloads" to "https://developer.android.com/studio/releases/platform-tools"
=> Fix SDK Tools Link

Document/0x06c-Reverse-Engineering-and-Tampering.md
For #1372 
Updated tracing iOS section. 
There is only Frida practically available for performing tracing. The existing content is for "method tracing", while I also added "native tracing", and pointed to Android section, as the content will remain the same. Let me know if this is okay, or we shall repeat some info for iOS.
=> 0x06c - iOS tracing section updated

Users.md
Websec had been on the list of users of the MSTG but was removed, citing a dead link. This is a request to re-add Websec to the list of users.
This PR closes #1748.
=> Add Websec.ca to list of users

Document/0x06g-Testing-Network-Communication.md
Added details about a new approach to implementing certificate pinning on iOS. As per Apple article https://developer.apple.com/news/?id=g9ejcf8y it is now possible to specify CA public key in Info.plist file, and this should be enough for pinning to work.
Also, replaced the code example with a reference to the official documentation and simplified the description.
___
___
This contribution was discussed with @sushi2k and @vixentael
=> New way to implement cert pinning for iOS

README.md
It will show a badge to directly open the project in vscode.
ref: https://open.vscode.dev/
=> Add Open in vscode Badge

Document/0x05d-Testing-Data-Storage.md
Fixed spelling from "wether" to "Whether" in "MSTG-STORAGE-10"
=> Minor spelling correction of "Wether" in MSTG-STORAGE-10

Document/0x06c-Reverse-Engineering-and-Tampering.md
Closes #1370.
Now we're consistent with Android.
=> 0x6c - Add section Loaded Native Libraries

Document/0x06a-Platform-Overview.md
adding visual studio app center
=> adding visual studio app center

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
`sudo gem install CocoaPods` does not work, and anyone doing this will end up with 
```
gem install CocoaPods
ERROR:  Could not find a valid gem 'CocoaPods' (>= 0) in any repository
```
The correct gem should be `cocoapods` found [here](https://rubygems.org/gems/cocoapods)
=> Fix typo in 0x06i-Testing-Code-Quality-and-Build-Settings.md

Document/0x06d-Testing-Data-Storage.md
Lvl 6 headings are not allowed.
=> fix lvl 6 heading

tools/docker/pandoc_makedocs.sh
Now sed runs in docker, no gsed needed in macos.
=> [Document Local Build] Remove gsed dependency on macOS

Document/0x02-Frontispiece.md, Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04h-Testing-Code-Quality.md
=> Removed title from Md link

Document/0x05e-Testing-Cryptography.md
Fixing typos, grammar, missing articles, etc.
=> Fixing typos and more in the Android Crypto Chapter

.github/workflows/config/mlc_config.json
Adding this website to the exception list for the link checker, as this URL sometimes gives a timeout.
=> Add damnvulnerableiosapp.com to exception list for link checker

Document/0x06e-Testing-Cryptography.md
This PR closes #1965
Additionally, I thought the first link for SecKey would be better in the [Apple Developer documents](https://developer.apple.com/documentation/security/seckey), so I am modifying it together.
=> Fix issue #1965

.github/workflows/docgenerator.yml, tools/scripts/mstg_to_html.sh, tools/scripts/yaml_to_excel.py
Here's the PR as discussed in https://github.com/OWASP/owasp-mstg/discussions/2082.
However, this is a mitigation measure specific to requirements with common test cases (e.g., V4 and V5).
It does not fulfill the requirements associated with V1 or those requiring multiple test cases.
The test case coverage in the new version of the checklist increases in +29 tests:
- ARCH +1
- STORAGE +2
- CRYPTO +1
- AUTH +19
- NETWORK +5
- PLATFORM +1
This PR closes #2084.
=> Increase Checklist Test Coverage Including Tests from the 0x04* Chapters

tools/docker/pandoc_makedocs.sh
The latest [pandocker 22.03](https://github.com/dalibo/pandocker/releases/tag/22.03) (released 9 days ago) seems to have some issues, since our document generation pipeline fails (since at least 4 days ago) and we didn't introduce any changes.
https://github.com/OWASP/owasp-mstg/runs/5673350862?check_suite_focus=true
```
Status: Downloaded newer image for dalibo/pandocker:stable
Error producing PDF.
! Missing \endcsname inserted.
<to be read again> 
\unhbox 
l.538 ....-6a6c200874bcb4cd/Images/OWASP_logo.png}
Error: Process completed with exit code 43.
```
Checking if we need a regression to [pandocker 22.01](https://github.com/dalibo/pandocker/releases/tag/22.01).
**UPDATE:** this PR's build works as expected. See https://github.com/OWASP/owasp-mstg/runs/5691764709?check_suite_focus=true
=> [Regression Test] pandocker 21.02

Document/0x06h-Testing-Platform-Interaction.md
=> Issue #2111 - Add information on enabling Safari Web Inspector on iOS

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> 0x04e - About OTP Authentication Checks

Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md, Document/0x06h-Testing-Platform-Interaction.md
=> Update Corellium info and about decrypting IPAs

Document/0x05b-Basic-Security_Testing.md
Added instructions explaining how to move the burp certificate from user to root store.
You can also add alternative certificate installation instructions. The current instructions download the cert outside android VM, push it and install it. This can all be done from within the Android VM as well.
The instructions would be as followed:
1. Start Burp and configure your Android VM Wi-Fi settings to use Burp proxy.
2. Visit http://burp, and download the certificate.
3. Rename the certificate to cacert.cer.
4. Open the file and you will be prompted to confirm installation of the certificate.
Let me know what you think about the alternative instructions as well and if it would fit in the document or not.
=> Added instructions explaining how to move certificate from user to root store

Document/0x05e-Testing-Cryptography.md, Document/0x06e-Testing-Cryptography.md
=> Fix Intros in Cryptography Chapters (by @NowSecure)

Document/0x04g-Testing-Cryptography.md
Updated CRYPTO section with information about export and import regulations for cryptography, describing why it matters for mobile apps. Added references to guidelines from Apple and Google and to governmental websites with the related information.
These changes were discussed with @sushi2k and @vixentael in a separate doc.
=> CRYPTO: Export and import crypto regulations

.github/labeler.yml, .github/workflows/labeler.yml
This PR closes partly Issue #2095.
It adds labels when changing data, as described in the issue. But it does not add labels to words in the PR title. Therefore an issue and a pull request from others is already open in actions/labeler. 
https://github.com/actions/labeler/pull/109
https://github.com/actions/labeler/issues/55
----------------------------------------------------
=> Auto-label PRs

.github/ISSUE_TEMPLATE/make-donation.yml, .github/workflows/spell-checker.yml, Document/0x04i-Testing-User-Privacy-Protection.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05e-Testing-Cryptography.md, Document/0x08a-Testing-Tools.md
This PR closes #2158 .
Feel free to correct my English when it is wrong.
---
The Tool APKLab also provides an automated solution for the [Patching, Repackaging, and Re-Signing](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#patching-repackaging-and-re-signing) section.
However, I have not added it here for the following reasons: 
- VScode is required as the execution environment.
- This section should provide more primitive knowledge.
=> add new testing tool APKLab

Document/0x05d-Testing-Data-Storage.md
- Recommend more input types disabling keyboard cache
- Add a check for SDK version
- Add a check for programmatic input type overwriting
=> Add static analysis details for Android keyboard cache

Document/0x04i-Testing-User-Privacy-Protection.md
=> Proofreading fixes 0x04i-Testing-User-Privacy-Protection.md

Document/0x05a-Platform-Overview.md
=> Proofreading fixes 0x05a-Platform-Overview.md

Document/0x05b-Basic-Security_Testing.md
part 1... mainly links
the links that I removed were broken
=> Proofreading fixes 0x05b-Basic-Security_Testing.md

Document/0x05b-Basic-Security_Testing.md
=> Proofreading fixes - last part - 0x05b

Document/0x05b-Basic-Security_Testing.md
=> Proofreading fixes part 2 - Android basic security testing

Document/0x05h-Testing-Platform-Interaction.md
This branch refactors 0x05h by reformatting to categorize by theory and tests. It also updates the testing sections overview to reflect the tests.
This PR closes #2217.
=> [Phase 1] Refactor 0x05h-Testing-Platform-Interaction.md (@NowSecure)

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x08a-Testing-Tools.md
This PR closes #2226.
New outline:
=> [Phase 1] Refactor 0x06j-Testing-Resiliency-Against-Reverse-Engineering.md

Document/0x06d-Testing-Data-Storage.md
Remove reference to `NSUserDefaults.synchronize` in iOS sample code, as Apple recommends not using it.
> this method is unnecessary and shouldn't be used
Source: https://developer.apple.com/documentation/foundation/nsuserdefaults/1414005-synchronize
This PR closes #2324.
=> Remove deprecated method from iOS sample code

docs/contributing/2_Getting_Started.md, tools/scripts/yaml_to_excel.py
This PR closes issue #2336 and discussions #2098.
- For your review, uploaded the checklist that I generated applying these changes.
- [Mobile_App_Security_Checklist_en.xlsx](https://docs.google.com/spreadsheets/d/1W7SCszh8vkqX_rYtNnh_B_quzdGzzK09/edit?usp=sharing&ouid=104469528966336890191&rtpof=true&sd=true)
- The first commit deals with issue #2336.
- The second commit is a simple refactoring of yaml_to_excel.py, and the third commit fixes a command omission that was accidentally found in the contributing guide.
=> Extend the status column in the MAS Checklists

Document/0x05d-Testing-Data-Storage.md
=> Proofreading fixes 0x05d part 1

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
=> #2295 [MSTG-CODE-2] Add a static analysis method (codesign/ldid)

Document/0x04h-Testing-Code-Quality.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
This PR closes #2212, #2218 and #2225
=> [Phase 1] Refactor Testing-Code-Quality.md

.github/workflows/docgenerator.yml
We need to undo the changes from https://github.com/OWASP/owasp-mastg/pull/2239 to be able to release.
This was the issue:
```
> Run softprops/action-gh-release@v[1](https://github.com/OWASP/owasp-mastg/actions/runs/4913261727/jobs/8773325420#step:6:1)
👩‍🏭 Creating new GitHub release for tag v1.6.0...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v1.6.0...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v1.6.0...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```
See solution here: https://github.com/softprops/action-gh-release/issues/236
=> Allow write from docgenerator

Document/0x05d-Testing-Data-Storage.md
=> Proofreading fixes 0x05d part 4

tools/scripts/yaml_to_excel.py
The old value of status value contained `H8` which causes the issue described in #2415. See screenshot below:
Remediation:
I changed the value of status_cells from `'H8:L400'` to `'I13:L400'`.
Effectiveness: 
I am not entirely sure the if the commit will help, was not able to generate a .xlsx checklist locally.
References:
The only reference that I have used was an earlier commit 3bfc72ebb60bfd6b09051568481a3343781b68a1, looking at the value of status_cells.
Possible next steps:
A separate rule should be made to fix 'status dropdown bar issue' in the remaining tabs (MASVS-AUTH MASVS-CODE), because status dropdown function is not applicable there on I13.
This PR closes #2415 except maybe for the MASVS-AUTH and MASVS-CODE tab.
=> Changed value of status_cells in yaml_to_excel.py

Document/0x06d-Testing-Data-Storage.md, tests/ios/MASVS-STORAGE/MASTG-TEST-0055.md
=> [ios_0x06d/0055] Fix the description of the keyboard cache location

tests/ios/MASVS-CODE/MASTG-TEST-0087.md
Update MASTG-TEST-0087 with radare2 and improved content.
=> Update MASTG-TEST-0087 "Make Sure That Free Security Features Are Activated"

techniques/android/MASTG-TECH-0044.md, techniques/android/MASTG-TECH-0045.md, techniques/ios/MASTG-TECH-0096.md, techniques/ios/MASTG-TECH-0097.md, tests/android/MASVS-STORAGE/MASTG-TEST-0011.md, tests/ios/MASVS-STORAGE/MASTG-TEST-0060.md, tools/generic/MASTG-TOOL-0036.md
=> Update r2frida guide examples to use `:` instead of `\` for command start

docs/contributing/1_How_Can_You_Contribute.md
We have had over a dozen translations of the MASVS and a few of the MASTG in the past, but we decided a few years ago to stop because the overhead is too much, as we have to contact dozens of people for each change, and the MASTG just changes too often and it will be impossible to keep it in sync through volunteer work. Also, the amount of content for the MASTG is too much to be translated by volunteers.
See the official statement here: https://mas.owasp.org/MASVS/
Starting with MASVS v2.0.0, translations will no longer be included to focus on the development of MASTG v2.0.0. We encourage the community to create and maintain their own translations. Thank you to all the past translators who generously volunteered their time and expertise to make the MASVS accessible to non-English speaking …
=> Remove "Translating the MASVS" from the docs

tools/ios/MASTG-TOOL-0050.md
- [✅] Your contribution is written in the 2nd person (e.g. you)
- [✅] Your contribution is written in an active present form for as much as possible.
- [✅] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [✅] Your contribution has proper formatted markdown and/or code
- [✅] Any references to website have been formatted as [TEXT](URL “NAME”)
- [✅] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)
This PR closes #2457 .
=> Add bagbak to iOS Tools

docs/javascripts/external_links.js
When you open https://mas.owasp.org/MASTG/ you will notice that external links (like github repo for example) will have small arrow icon and _blank attribute that will open the link in the new tab. But https://mas.owasp.org/MASVS/ page doesn't have the same behavior.
This PR modifies the code to enhance the user experience on the MASVS page (https://mas.owasp.org/MASVS/) by ensuring that external links open in a new tab, similar to the behavior on the MASTG page (https://mas.owasp.org/MASTG/). 
This change involves updating the checking if the path starts with '/MASTG' or '/MASVS' and applying the necessary attributes to external links accordingly. It also add `document$.subscribe()` so the code still executed when page navigate (reference: …
=> Update external_links.js to fix link behavior on MASVS page

tests/ios/MASVS-CODE/MASTG-TEST-0087.md
The code block under "Dynamic Analysis"  is not closed properly. 
As a result, the entire section of  "iOS Anti-Reversing Defenses" topic is included inside a code block on page no. 506 of MASTG pdf release v1.7.0
=> Proofreading fix on MASTG-TEST-0087.md -> Make Sure That Free Security Features Are Activated( by @appknox )

tests/ios/MASVS-PLATFORM/MASTG-TEST-0070.md
"The code block under "Resulting in" is not closed properly. 
As a result, the entire section of  "iOS Code Quality and Build Settings" topic is included inside a code block on page no. 497 & 498 of MASTG pdf release v1.7.0
=> Proofreading fix on MASTG-TEST-0070.md -> Testing Universal Links ( by @appknox )

tests/ios/MASVS-CODE/MASTG-TEST-0085.md
The code block under "Listing Application Libraries"  is not closed properly. 
As a result, the entire section of  "Make Sure That Free Security Features Are Activated" topic is included inside a code block on page no. 505 of MASTG pdf release v1.7.0
=> Proofreading fix on MASTG-TEST-0085.md -> Checking for Weaknesses in Third Party Libraries ( by @appknox )

.github/workflows/build-website.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docgenerator.yml, .github/workflows/markdown-linter.yml, .github/workflows/spell-checker.yml, .github/workflows/url-checker-pr.yml, .github/workflows/url-checker.yml
Bump:
- Checkout action to v4
- Setup python action to v5
- Codeql analyze action to v2 (v1 was deprecated early 2023)
- Download artifact action to v4
- Upload artifact action to v4
=> CI: update github action versions

tests/android/MASVS-STORAGE/MASTG-TEST-0001.md, tests/ios/MASVS-STORAGE/MASTG-TEST-0052.md
The MASTG in its version 1.7.0 and earlier recommended to encrypt all sensitive data in the internal memory of an app, even for L1 apps. However, the internal memory on Android and iOS is considered safe enough. Therefore, we are updating the recommendation to reflect this and allow L1 apps to store unencrypted data in internal storage. L2 apps must also encrypt data on internal storage. The recommendation for external storage does not change.
=> Updated L1 vs L2 recommentation for MASVS-STORAGE

techniques/ios/MASTG-TECH-0090.md, techniques/ios/MASTG-TECH-0092.md
Fix MASTG-TECH-0090 which was missing content.
=> Fix iOS patching technique

Document/0x05d-Testing-Data-Storage.md, Document/0x06d-Testing-Data-Storage.md
This PR closes #1951
Long delay and update, added both iOS and Android examples
=> Updated Decrypting Realm Databases in 0x05d - Testing Data Storage and 0x06d-Testing-Data-Storage 

tools/ios/MASTG-TOOL-0101.md, tools/ios/MASTG-TOOL-0102.md
=> [New Tool] add ios-app-signer (by @appknox)

src/pandocker/pandoc_makedocs.sh
The new release https://github.com/dalibo/pandocker/releases/tag/24.05 is breaking our doc generation. So we're going back to the previous release 23.03.
```
Digest: sha256:3a0436dfa85c5b12580afc921ebd65097dce3cacf2befdcccac5898e472565ce
Status: Downloaded newer image for dalibo/pandocker:stable
Warning:  Could not fetch resource Images/Chapters/0x03/owasp-mobile-overview.png%22%20alt=%22image: replacing image with description
Error producing PDF.
! Missing \endcsname inserted.
<to be read again> 
\__kernel_tl_set:Nx 
l.456 ...aperwidth,height=\paperheight]{cover.pdf}
Error: Process completed with exit code 43.
```
=> Update pandoc_makedocs.sh for pandocker 23.03

techniques/ios/MASTG-TECH-0056.md
Cydia impactor is quite outdated and Sideloadly is an actively maintained alternative.
=> Update IPA installation

README.md
Closes #2783
Remove the "About Hybrid Apps" section from the `README.md` file as this disclaimer it's available within the MASTG.
=> Remove 'About Hybrid Apps' from README

docs/hooks/maswe-beta-banner.py
Closes #2795
Add a newline character at the end of the 'note' addition in `docs/hooks/maswe-beta-banner.py`.
=> Fix MASWE note display issue

.github/workflows/build-android-demos.yml
Closes #2829
Add a new GitHub action to build APKs for each `MASTG-DEMO-XXXX` folder in the `demos/android` directory.
* Add a new workflow file `.github/workflows/build-android-demos.yml`.
* Clone the `MASTestApp-Android` repository.
* Replace `MastgTest.kt` and/or `AndroidManifest.xml` files in `MASTestApp-Android` if they exist in the demo folder.
* Build the APK for each demo folder.
* Upload the resulting APKs as artifacts with the name of the demo as the APK's name.
=> Add Android demo APKs GitHub action

demos/android/MASVS-CRYPTO/MASTG-DEMO-0007/MASTG-DEMO-0007.md, demos/android/MASVS-CRYPTO/MASTG-DEMO-0008/MASTG-DEMO-0008.md, demos/android/MASVS-STORAGE/MASTG-DEMO-0003/MASTG-DEMO-0003.md, demos/android/MASVS-STORAGE/MASTG-DEMO-0004/MASTG-DEMO-0004.md, demos/android/MASVS-STORAGE/MASTG-DEMO-0005/MASTG-DEMO-0005.md, techniques/android/MASTG-TECH-0014.md, tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0206.md, tools/generic/MASTG-TOOL-0110.md
https://github.com/semgrep/semgrep
=> [MASTG-TOOL-0110] Add semgrep

techniques/android/MASTG-TECH-0012.md, tools/generic/MASTG-TOOL-0032.md
A fix for #2824 
We can still add separate pages in the future and then link to those pages from the list on this page. I mostly wanted to already remove the very outdated references for SSL pinning.
=> Fixes #2824

tests/ios/MASVS-RESILIENCE/MASTG-TEST-0084.md
Maybe good to reference this document for Swift developemtn https://www.swiftbysundell.com/articles/using-compiler-directives-in-swift/
=> defined variables can't contain dashes

techniques/android/MASTG-TECH-0109.md, tools/android/MASTG-TOOL-0120.md, tools/network/MASTG-TOOL-0115.md
The content has been revised and restructured for #2897
=> Proof-Reading: HTTP Tookit (by @appknox)

tests-beta/android/MASVS-NETWORK/MASTG-TEST-0217.md, tests-beta/android/MASVS-NETWORK/MASTG-TEST-0218.md
=> Fix quotes 

tools/ios/MASTG-TOOL-0122.md
Fix a typo in a recently added tool name
=> Fix typo MASTG-TOOL-0122 title name

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md, techniques/android/MASTG-TECH-0115.md, techniques/ios/MASTG-TECH-0082.md, techniques/ios/MASTG-TECH-0118.md, tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-1.md, tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-2.md, tests-beta/ios/MASVS-CODE/MASTG-TEST-0x87-3.md, tests/ios/MASVS-CODE/MASTG-TEST-0087.md
=> Port MASTG test 0087 (by @guardsquare)

tests-beta/android/MASVS-STORAGE/MASTG-TEST-0203.md, tests-beta/android/MASVS-STORAGE/MASTG-TEST-0231.md, tests-beta/android/MASVS-STORAGE/MASTG-TEST-0x03.md, tests/android/MASVS-STORAGE/MASTG-TEST-0003.md
=> Port MASTG-TEST-0003 (by @guardsquare)

tools/ios/MASTG-TOOL-0056.md
Keychain dumper tool page was outdated. This procedure should now work on rootless jailbreaks.
=> Update MASTG-TOOL-0056 with new Keychain-Dumper tool repo

docs/hooks/add-tags.py, docs/hooks/create_dynamic_tables.py, docs/hooks/maswe-beta-banner.py, mkdocs.yml, tests/android/MASVS-STORAGE/MASTG-TEST-0001.md, tests/android/MASVS-STORAGE/MASTG-TEST-0003.md, tests/ios/MASVS-RESILIENCE/MASTG-TEST-0081.md, tests/ios/MASVS-RESILIENCE/MASTG-TEST-0083.md
Introduce deprecation notes and status indicators for MASTG tests, including draft and deprecated banners.
The deprecated banners for MASTG v1 tests also list the V2 tests covering for the old test.
Update theme and extra sections to reflect these statuses.
=> Add deprecation notes and status for MASTG tests

tests-beta/ios/MASVS-CODE/MASTG-TEST-0228.md
Removed 2nd bullet point of the list because was referring to shared libraries while the test focus only on the binary.
Note: I discussed about that with Carlos directly on Slack.
> The test indicates:
>   - “Shared libraries (dylibs and frameworks) are inherently position-independent (PIE)”
>   - “This test case checks if the main executable is compiled with PIE.”
>   So we just need to check the main binary on iOS.
=> Update MASTG-TEST-0228 to remove a step that isn't needed

.github/workflows/build-ios-demos.yml
This PR introduces a GitHub Actions workflow to automate the build process for all iOS demo applications. The workflow dynamically discovers demo projects and generates unsigned `.ipa` files that can be downloaded and tested on jailbroken devices.
- **Automatic Discovery:**  
- Finds all demo directories under `demos/ios/` matching the pattern `MASTG-DEMO-*`.
- Builds each demo separately using a dynamic matrix strategy.
- **Build Process:**
- Installs necessary dependencies (`ldid`, `cocoapods`).
- Replaces required project files (e.g., `MastgTest.swift`, `Info.plist`) from each demo.
- Updates the iOS deployment target to **14.4** for compatibility.
- Compiles the project with Xcode without code signing.
- Manually packages the app into an `.ipa` file.
- **Artifact Upload:**  
- The …
=> Add GitHub Actions workflow to build iOS demos (by @NowSecure)

weaknesses/MASVS-AUTH/MASWE-0028.md, weaknesses/MASVS-AUTH/MASWE-0030.md, weaknesses/MASVS-AUTH/MASWE-0031.md
- Update all CWE IDs on MASWE elements of MASVS-AUTH-3
- MASWE-0028 may also be related to **[CWE-308: Use of Single-factor Authentication](https://cwe.mitre.org/data/definitions/308.html)**  since "no MFA" can be considered a "MFA implementation lacking". To comprehend CWE-308 in the MASWE list, please consider change the title or add this as Relevant Topic of MASWE-0028, or add a new MASWE element.
=> Update CWE mapping on MASWE elements of MASVS-AUTH-3

weaknesses/MASVS-AUTH/MASWE-0041.md, weaknesses/MASVS-AUTH/MASWE-0042.md, weaknesses/MASVS-AUTH/MASWE-0043.md, weaknesses/MASVS-AUTH/MASWE-0044.md, weaknesses/MASVS-AUTH/MASWE-0045.md, weaknesses/MASVS-AUTH/MASWE-0046.md
- Update all CWE IDs on MASWE elements of MASVS-AUTH-1
=> Update CWE mapping on MASWE elements of MASVS-AUTH-2

weaknesses/MASVS-NETWORK/MASWE-0048.md, weaknesses/MASVS-NETWORK/MASWE-0051.md, weaknesses/MASVS-NETWORK/MASWE-0052.md
- Update all CWE IDs on MASWE elements of MASVS-NETWORK-1
- Skipped MASWE-0049 due to possible deprecation
=> Update CWE mapping on MASWE elements of MASVS-NETWORK-1

weaknesses/MASVS-PLATFORM/MASWE-0053.md, weaknesses/MASVS-PLATFORM/MASWE-0054.md, weaknesses/MASVS-PLATFORM/MASWE-0055.md, weaknesses/MASVS-PLATFORM/MASWE-0056.md, weaknesses/MASVS-PLATFORM/MASWE-0057.md
- Update all CWE IDs on MASWE elements of MASVS-PLATFORM-3
- MASWE-0057 is missing because still under review; CWE-20: Improper Input Validation and CWE-284: Improper Access Control are suggested.
=> Update CWE mapping on MASWE elements of MASVS-PLATFORM-3.

demos/android/MASVS-CRYPTO/MASTG-DEMO-0017/MASTG-DEMO-0017.md
For the demo of the test, MASTG-DEMO-0017: Use of Hardcoded AES Key in SecretKeySpec with semgrep, the reversed Java code in the Sample section is not rendered because the markdown file was missing the Java code filename. With this PR the filename is updated in the Sample section so that both the Kotlin code and reversed Java code are visible.
=> Fixed Missing Reversed Java Code in the MASTG-DEMO-0017

weaknesses/MASVS-PRIVACY/MASWE-0117.md
=> Add MASWE-0117 - Inadequate Permission Management

.github/workflows/build-android-demos.yml
- simplify shell scripts.
- caches the MASTestApp-Android App in order to speed up the app demo builds.
- reduces build time from 18 min to <5 min.
This PR closes #3156.
=> build-android-demos.yml: simplify shell scripts and cache Android app build

tests/ios/MASVS-CRYPTO/MASTG-TEST-0061.md, tests/ios/MASVS-CRYPTO/MASTG-TEST-0062.md
- MASTG-TEST-0209 MASTG-TEST-0210 will cover MASTG-TEST-0061 in v2
- MASTG-TEST-0213, MASTG-TEST-0214 will cover MASTG-TEST-0062 in v2
This PR closes #2945 closes #2943
=> MASTG v1->v2 MASTG-TEST-0061 Verifying the Configuration of Cryptographic Standard Algorithms (ios) and MASTG-TEST-0062 Testing Key Management (ios)

.github/workflows/build-android-demos.yml, .github/workflows/build-ios-demos.yml, demos/android/MASVS-CODE/MASTG-DEMO-0025/MASTG-DEMO-0025.md, demos/ios/MASVS-CRYPTO/MASTG-DEMO-0011/MASTG-DEMO-0011.md, docs/hooks/github_api.py
This PR closes #3204 
This PR optimizes the GitHub Action for building Android and iOS demos by modifying its behavior based on the event type:
- For push to master: The workflow remains unchanged and builds all Android demos.
- For pull requests: The build now runs only if files within `demos/android/**` or `demos/ios/**` have changed, reducing unnecessary builds. This is achieved by using `git diff` to detect modified files and updating the matrix accordingly.
This improves CI efficiency by avoiding redundant builds when no relevant changes are made.
**Additional changes: Demo download buttons**
This PR also updated the script that ensures that the last successful run of the GitHub Action was on the master branch. 
- Script: `docs/hooks/github_api.py`
- Used from: …
=> Only run APK/IPA builds on changes demos in PRs only

docs/hooks/create_dynamic_tables.py, docs/hooks/maswe-beta-banner.py
Improve the visibility of demo statuses in dynamic tables and introduce a draft banner for demos that are not yet created.
=> Add demo status display and draft banner for demos

docs/hooks/maswe-beta-banner.py
This PR includes updates to the `docs/hooks/maswe-beta-banner.py` file to correct the GitHub Issues query URL (remove the `is:issue` filter) in several draft banner functions.
- `get_maswe_draft_banner` 
- `get_tests_draft_banner`
- `get_demos_draft_banner`
=> Correct search query for issue or PR to include description

demos/android/MASVS-PLATFORM/MASTG-DEMO-0031/MASTG-DEMO-0031.md, demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/MASTG-DEMO-0032.md
Introduce draft demos utilizing Frida and semgrep to identify WebView settings that permit local file access in Android applications.
=> Add draft demos for detecting local file access in WebViews

.github/workflows/build-android-demos.yml, .github/workflows/build-ios-demos.yml
- Fix broken output formatting in matrix extraction.
- Streamline file copying logic for Android demo builds.
- Add copying of: filepaths.xml, network_security_config.xml, backup_rules.xml, data_extraction_rules.xml
Thanks @javier-ruiz-b for the fixes
=> Refactor build workflows for Android and iOS demos

.github/workflows/build-android-demos.yml
Update the build workflow to explicitly copy each required file for the Android demo, ensuring all necessary files are included for a successful build.
=> Fix Android demo build workflow by explicitly copying individual files

weaknesses/MASVS-NETWORK/MASWE-0052.md
Corrected a typo in the `cwe` mappings of `weaknesses/MASVS-NETWORK/MASWE-0052.md` by replacing a period with a comma.
=> Update MASWE-0052.md (fix missing coma in cwes)

.github/workflows/check-duplicate-ids.yml
Fix duplicate ID checker GitHub Action to handle PRs with no comments in `.github/workflows/check-duplicate-ids.yml`.
Issue: the workflow failed when running on PRs without any existing review comments.
Key fixes:
- Added proper error handling around comment operations
- Created a helper function to generate consistent notification messages
- Added a fallback to issue comments when review comments can't be created
- Simplified the workflow and added more comments
=> Fix duplicate ID checker to handle PRs with no existing comments

demos/android/MASVS-STORAGE/MASTG-DEMO-0034/MASTG-DEMO-0034.md, demos/android/MASVS-STORAGE/MASTG-DEMO-0035/MASTG-DEMO-0035.md
Update demo IDs for two Android backup and restore app data examples to ensure they are unique and correctly referenced.
=> Fix demo IDs for backup and restore examples

tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0255.md, tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0256.md, tests-beta/android/MASVS-PRIVACY/MASTG-TEST-0257.md
Introduce three new draft test cases focused on privacy: 
- checking for minimized permission requests
- ensuring a rationale is provided for permissions
- verifying the reset of unused permissions.
=> Add new drafts for privacy test cases in Android

tests-beta/android/MASVS-STORAGE/MASTG-TEST-0262.md
Introduce a draft test to verify the presence of backup rules in the AndroidManifest.xml, ensuring sensitive data is not included in backups.
=> Add draft for MASTG-TEST-0262: Backup Configurations Not Excluding Sensitive Data test

demos/android/MASVS-RESILIENCE/MASTG-DEMO-0038/MASTG-DEMO-0038.md, demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/MASTG-DEMO-0039.md, tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0264.md, tests-beta/android/MASVS-RESILIENCE/MASTG-TEST-0265.md
Introduce DRAFT demos and tests about `StrictMode` usage in Android applications, both at runtime using Frida and statically using Semgrep.
=> Add drafts for MASTG-TEST-0264, MASTG-TEST-0265, MASTG-DEMO-0038, MASTG-DEMO-0039 

src/scripts/requirements.txt
The problem was `mkdocs-awesome-pages-plugin`, using any version above `2.9.2` results in the blog index disappearing. This PR pins that dependency to `2.9.2` and other primary dependencies to the latest versions as of today. 
Closes #3243
=> Fix broken blog by pinning dependencies (Workaround)

weaknesses/MASVS-PLATFORM/MASWE-0069.md
This PR adds a new mapping under `android-risks` to include a link to the Android developer documentation on unsafe file inclusion in WebView to MASWE-0069.
=> MASWE-0069 draft: Add android risk reference for WebViews local resource access

tests/ios/MASVS-AUTH/MASTG-TEST-0064.md
Removed the `status: deprecated` status and other fields.
=> Remove deprecation note in MASTG-TEST-0064 (added by mistake)

weaknesses/MASVS-CRYPTO/MASWE-0018.md
* Fixed URL https://developer.apple.com/documentation/security/restricting-keychain-item-accessibility
* Revised the draft description to clarify that cryptographic keys can be bound to the current device in addition to being accessible only under strict conditions.
* Added a new topic to emphasize the importance of device-bound or non-transferable cryptographic keys (e.g., iOS `ThisDeviceOnly`).
=> Update MASWE-0018.md draft

docs/hooks/maswe-beta-banner.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Resolve logger warnings in MkDocs plugin

docs/hooks/create_dynamic_tables.py
This PR updates the URLs used in the `status` field for draft items across multiple functions in `docs/hooks/create_dynamic_tables.py`. The changes simplify the query parameter in the GitHub issue links by removing `is%3Aissue`.
=> Update create_dynamic_tables.py to search for issues and PRs

weaknesses/MASVS-CODE/MASWE-0088.md
* Added a new `android-risks` section with a link to Android's official documentation on unsafe deserialization risks.
* Added multiple references under the `refs` section, including a Black Hat presentation, a GitHub repository, an OWASP cheat sheet, and a blog post on exploiting memory corruption vulnerabilities on Android.
=> Update MASWE-0088 Draft

weaknesses/MASVS-STORAGE/MASWE-0002.md
This MASWE would fit the insecure usage of keychain too.
=> Update MASWE-0002 Draft Info

docs/contributing/7_Run_the_Website.md
This pull request adds a new guide to the `docs/contributing/7_Run_the_Website.md` file, providing detailed instructions on how to set up and run the OWASP MAS website locally. The guide is structured with clear steps and includes prerequisites, setup commands, and debugging tips.
=> Add docs for run website locally

.github/workflows/build-website.yml, .github/workflows/check-website-build.yml
Closes #3324
* [`.github/workflows/check-website-build.yml`](diffhunk://#diff-6284d2d945d9134c3769fe6d8a0f2749b5568872171ba07696aecf158a1b0b5bR1-R40): Added a new workflow named "Check Website Build" to validate the website's build process on pull requests without deploying it.
* [`.github/workflows/build-website.yml`](diffhunk://#diff-bbc95c597ac5c7abf10c841501a235bb91d15c710ca51a5f343cee0f2a7541beL14-R14): Changed the `fetch-depth` parameter in the `actions/checkout` step from `0` to `1` to optimize the checkout process by fetching only the latest commit.
=> Add GitHub Actions workflow for website build checks

src/scripts/structure_mastg.sh
Without the *, it will copy the Images folder into docs/assets/Images rather than the files. This means images end up in the wrong folder for the website, resulting in 404 images.
=> Fix image copy

demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/output.txt, demos/android/MASVS-RESILIENCE/MASTG-DEMO-0027/script.js
This PR enhances the existing Frida demo script to surface return values and flag names in the logs and updates the sample output accordingly.
- The `KeyguardManager.isDeviceSecure` hook now logs the method’s boolean result.
- The `BiometricManager.canAuthenticate` hook is refactored to map integer flags and result codes to human-readable names.
- The example output is updated to show the new “flags” and “RESULT” formats and trims unrelated stack frames.
=> Update MASTG-DEMO-0027 frida script to lookup flags and result

demos/android/MASVS-CRYPTO/MASTG-DEMO-0012/MastgTest.kt
The code had a typo but actually the comments are redundant as the code is clear enough
=> remove redundant comments

docs/hooks/create_dynamic_tables.py
Closes #3405
on_config runs before on_pre_build so the create_dynamic_tables hook was collecting info before the files were copied in combine-repos.
Now create_dynamic_tables hook also uses on_pre_build with a lower priority than combine-repos.
=> Change plugin order for table generation

techniques/ios/MASTG-TECH-0054.md
This PR closes (I didn't create an issue)
MASTG-TECH-0054 (Obtaining and Extracting Apps) mistakenly cross-references `ios-deploy` when it meant to reference `debug.py`. I updated the reference so that it points to the correct tool.
-------------------
[x] I have read the contributing guidelines.
=> Fixed cross-ref to wrong tool.

.github/workflows/build-website.yml
Replace the reusable workflow with a direct trigger for deployment in the GitHub Actions workflow, streamlining the deployment process.
=> Refactor GitHub Actions workflow for direct deployment trigger

.github/workflows/check-website-build.yml
This pull request updates the workflow configuration for building the website to ensure that pull request builds use the correct source reference. The main change is to how the `sources_override_json` is constructed, switching from using the branch name to using the pull request number.
Workflow configuration update:
* [`.github/workflows/check-website-build.yml`](diffhunk://#diff-6284d2d945d9134c3769fe6d8a0f2749b5568872171ba07696aecf158a1b0b5bL12-R12): Changed the `sources_override_json` input to reference the pull request number (`refs/pull/{number}/head`) instead of the branch name (`refs/heads/{branch}`), ensuring builds use the actual PR source.
=> Update sources_override_json for pull request builds to consider forks

best-practices/MASTG-BEST-0015.md, best-practices/MASTG-BEST-0016.md, best-practices/MASTG-BEST-0017.md, best-practices/MASTG-BEST-0018.md, best-practices/MASTG-BEST-0019.md, demos/android/MASVS-PLATFORM/MASTG-DEMO-0062/MASTG-DEMO-0062.md, demos/android/MASVS-PLATFORM/MASTG-DEMO-0063/MASTG-DEMO-0063.md, knowledge/android/MASVS-PLATFORM/MASTG-KNOW-0105.md, knowledge/android/MASVS-PLATFORM/MASTG-KNOW-0106.md, knowledge/android/MASVS-PLATFORM/MASTG-KNOW-0107.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0292.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0293.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0294.md
Introduce placeholders for various best practices, tests, and demo topics related to preventing screenshots and screen recordings in Android applications. These additions aim to enhance documentation and testing coverage for sensitive data protection.
=> Add placeholders for best practices, tests, and demos

.github/instructions/markdown.instructions.md, .github/instructions/mastg-apps.instructions.md, .github/instructions/mastg-best-practice.instructions.md, .github/instructions/mastg-demo.instructions.md, .github/instructions/mastg-frida-scripts.instructions.md, .github/instructions/mastg-knowledge.instructions.md, .github/instructions/mastg-mitmproxy-scripts.instructions.md, .github/instructions/mastg-r2-scripts.instructions.md, .github/instructions/mastg-rules.instructions.md, .github/instructions/mastg-techniques.instructions.md, .github/instructions/mastg-test.instructions.md, .github/instructions/mastg-tools.instructions.md, .github/instructions/porting-mastg-v1-tests-to-v2.instructions.md
Improve grammar and clarity in markdown instructions.
The target branch is **not** the main branch.
=> Improve grammar and clarity in markdown instructions.
