Document/Testcases/0x06a_OMTG-DID_Android.md
Adding Test Case : OMTG-DATAST-001: Test Sensitive Data Storage
=> OMTG-DID-001: Testing SSL Pinning

generate_document.sh
updated generate_document.sh so it includes testcases
=> update generate doc

Document/0x08-Testing-Tools.md, README.md
=> Update Testing Tools and Responsibility for Testing tools on README

Document/0x04a-Android.md
=> fixed android intents explanation

Document/0x05b-Testing-Process-and-Techniques-iOS.md
=> Added Method to recover ipa on non-jailbroken devices

Document/0x05a-Basic-Security-Testing-Android.md
Kept original content and added several other topics with a first level of details.
=> 0x05a - More detailed ToC

Document/0x07a-Security-Testing-SDLC.md
More content added to security testing in SDLC chapter.
=> Add high-level content to chapter 0x07a

Document/0x04a-Android.md
Please review. Opinions and suggestions are welcome.
=> Update Document/0x04a-Android.md - Added Permissions

Document/0x04a-Android.md
Also removed part of the TODO list at the beginning of the chapter for things that have been written.
=> Add paragraph on Dalvik VS ART

Document/0x05a-Platform-Overview.md
Also reordered paragraphs on Activities and Fragment together, and Intents and Broadcast Receivers together.
=> Add paragraph on application lifecycle and elements on activities

Document/0x05a-Platform-Overview.md
+ add a reference at the bottom of the chapter
=> Add elements on APIs

Document/0x05a-Platform-Overview.md
Also added a reference at the end of chapter
=> Add elements on fragments

Document/0x05h-Testing-Platform-Interaction.md
Update paragraph to bullet list.
=> Update 0x05h-Testing-Platform-Interaction.md - Permissions

Document/0x05b-Basic-Security_Testing.md
=> 0x5b - typo

Document/0x04-Testing-Processes-and-Techniques.md
Things cannot possess things :-) ('s is only for living elements, like people or animals)
=> 0x4 - grammar change

Document/0x04-Testing-Processes-and-Techniques.md
Changed 'disassembler' to 'disassembling'
=> 0x4 - typo

Document/0x05a-Platform-Overview.md
I am responsible for this chapter and authored part of the text, so I made the changes on my own. I will let others work on their chapters.
(also fixed minor issues)
=> 0x5a - Changed "Application" to "App"

Document/0x07-Security-Testing-SDLC.md
First introduction section on DevOps
=> Add the first DevOps section

Document/0x04-Testing-Processes-and-Techniques.md
=> 0x4 - Add 'system'

Document/0x04-Testing-Processes-and-Techniques.md
=> 0x4 - Fixed typo "think about ... into"

Document/0x05d-Testing-Data-Storage.md
Information is always singular
=> 0x5d - Fixed typo ('these') (2)

Document/0x05d-Testing-Data-Storage.md
'Information' is always singular -> 'this information' is the only suitable option
=> 0x5d - Fixed typo ('these')

Document/0x05d-Testing-Data-Storage.md
Something is available to someone for a purpose
=> 0x5d -  Fixed typo ('for' -> 'to')

Document/0x05d-Testing-Data-Storage.md
Things cannot own things in English
=> 0x5d - removed 's'

Document/0x05d-Testing-Data-Storage.md
I double-checked, the change seems to be recorded. Let's see...
=> 0x5d - Fixed typo ('on' -> 'at') 2nd version

Document/0x07-Security-Testing-SDLC.md
secure software testing was a very vague term
either it should be software testing or security testing in SDLC
=> Changes secure software testing

Document/0x04-Testing-Processes-and-Techniques.md
Also updated numbers pointing to references.
=> 0x04- Moved all references at the end of chapter

Document/0x05b-Basic-Security_Testing.md
Completed QA for the 0x05b section 
+ added OS version checks in the preparation step
=> 0x05b - QA Completed

Document/0x05d-Testing-Data-Storage.md
'the external service' -> 'external services'
=> 0x5d - Singular -> plural

Document/0x05a-Platform-Overview.md
Plus add an introduction paragraph.
Plus minor fixes.
=> 0x5a - Harmonize todos through the guide

Document/0x05b-Basic-Security_Testing.md
Plus deletion of paragraph on Attack Methodology (redundant with information in 0x4).
Minor fixes.
=> 0x5b - Harmonize todos through the guide

Document/0x05h-Testing-Platform-Interaction.md
=> 0x5h - Harmonize todos through the guide

Document/0x05c-Reverse-Engineering-and-Tampering.md
Added some notes on the use of Frida extracted and adapted from my tutorials.
=> Additions on the use of Frida

Document/0x06d-Testing-Data-Storage.md
1. Overview added
2. Black-box Testing markdown fixed
3. White-box Testing improved
https://github.com/OWASP/owasp-mstg/issues/338
=> Testing for Sensitive Data in the Keyboard Cache

Document/0x03-Overview.md
Saw a grammar issue, so I'm proposing a fix.
=> Restructure of incomplete/redundant sentence

Document/0x04-Testing-Processes-and-Techniques.md
Worked on the TODO item regarding the writeup on Static Analysis and Dynamic Analysis
=> Added info on Static Analysis and Dynamic Analysis

Document/0x03-Overview.md
Worked on the TODO item regarding [What is the OWASP Mobile Top 10].
=> Added info on OWASP Mobile Top 10

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> abd jdwp --> adb jdwp

Document/0x05c-Reverse-Engineering-and-Tampering.md
- Clarification on the shortcut (if you're just reading the text it's a little unclear what it does)
- Correction on Frida intro: Device doesn't need to be rooted since there are other methods of injecting Frida. (We might want to elaborate on that in a separate subsection)
- Spelling / grammer corrections
=> Small corrections on Android Reversing

Document/0x06h-Testing-Platform-Interaction.md
Please review section Testing JavaScript Execution in WebViews.
=> Finished section Testing JavaScript Execution in WebViews

Document/0x05e-Testing-Cryptography.md
Add two deprecated algorithm : RC4, Blowfish
=> Add two deprecated algorithm

Document/0x05d-Testing-Data-Storage.md
0x05d Added Drozer usage guides for testing content providers
=> 0x05d Added Drozer usage guides for testing content providers

Document/0x05b-Basic-Security_Testing.md
Added Drozer installation and startup steps to setting up environment section of guide.
=> 0x05b Added Drozer installation and startup steps

Document/0x05c-Reverse-Engineering-and-Tampering.md
Noticed a slight error in Android SDK versions. Corrected in this PR.
=> Corrected SDK Versions

Document/0x05h-Testing-Platform-Interaction.md
Currently working on added Drozer usage snippets to relevant sections throughout the guide. This PR covers app permissions.
=> 0x05h - Added Drozer Snippet for Getting App Permissions

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
Added Drozer Snippets for Android Debuggable Issue
=> Added Drozer Snippets for Android Debuggable Issue

Document/0x04-Testing-Processes-and-Techniques.md
And also modified the URLs to make them suitable for "printing" as git book
=> Added Write-up on Different Types of Mobile Apps

Document/0x06a-Platform-Overview.md
Simply modified the URLs and wordings to make content suitable for "printing" to git book.
=> Modified the URLs and Wordings

Document/0x04-Testing-Processes-and-Techniques.md
Added write-up on testing methods, short intro on fuzzing and fixed some formatting, typo and links/urls
=> Added write-up on testing methods and etc.

Document/0x06g-Testing-Network-Communication.md
=> 480 - Add ATS

Document/0x06e-Testing-Cryptography.md
Also fixed some typo and add some comments
=> Added Write-up on Testing Random Number Generation

Document/0x05f-Testing-Local-Authentication.md
Some proof-reading for https://github.com/OWASP/owasp-mstg/issues/285 . 
I also modified the code a little bit as there was some copy-pasting from http://www.androidauthority.com/how-to-add-fingerprint-authentication-to-your-android-app-747304/ ("FingerprintHandler class") and the example didn't really work.
=> Reviewed 0x05f-Testing-Local-Authentication

Document/0x05d-Testing-Data-Storage.md
just stumbled upon some smaller typos while reading. 
also tried to get some sentences straight.
=> Smaller Typo/ Grammar Fix

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
As described in https://github.com/OWASP/owasp-mstg/issues/454
=> Simplified the possible in-depth explanation on additional debug functionality

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
This paragraph is included at the beginning of this section.
=> Remove a duplicated paragraph

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
small fix as asked by @sushi2k
=> Updated 0x06j according to feedback

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Even though this branch is focussed on iOS, I had to update the android first. Hope to do 2 PRs from the branch, but I wanted to get started by just updating the Android part so I can mimic in in iOS as well.
=> First pass review for Android file storage

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x07a-Testing-Authentication-and-Session-Management.md
=> StrictMode

Tools/generate_document.sh
Some sections were added/renamed. This PR makes it possible to generate the docx file with pandoc.
=> Update doc list in `Tools/generate_document.sh`

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Hi all,
this is my first iteration for handling exceptions in iOS. I am not so sure about the content yet, please provide as much feedback as possible. 
With kind regards,
Jeroen
=> 0x6i/exception handling (WIP)

Document/0x07a-Testing-Authentication-and-Session-Management.md
+ link on server-side blacklisting
=> Updated stateless authentication logout

Document/0x05e-Testing-Cryptography.md
* Further addressing #507 
* Work in progress
=> More details for cryptographic standards and secure random

Document/0x07a-Testing-Authentication-and-Session-Management.md
Original TODO: explain timeout for Stateless and give examples of implementations
=> Completed TODO for session timeout

Document/0x05e-Testing-Cryptography.md, Document/0x05g-Testing-Network-Communication.md
This is a first fix for https://github.com/OWASP/owasp-mstg/issues/517
=> Sec providers android

style_guide.md
Added content writing guidance and language section
=> Updated Style Guide

Document/0x05d-Testing-Data-Storage.md, Document/0x06d-Testing-Data-Storage.md
See  https://github.com/OWASP/owasp-mstg/issues/541
=> Added Realm data for both android and iOS 

Document/0x07c-Testing-Cryptography.md
An intermediate check-in. Restructured sections, rewritten introduction, continuing with individual sections.
The ordering of subsections is as follows:
- crypto-specific problems (custom algs, insecure algs, misconfiguration and misuse)
- keys (hardcoding and generation)
- sensitive data (storage protection techniques and pwd storage considerations)
=> Denis's edits to 0x07c-Testing-Cryptography.md

Document/0x05b-Basic-Security_Testing.md
* Minor formatting, spelling, terminology fixes in the whole `0x05b` document
* Edits to section 01
=> Edits/grammar 0x05b, part 01

style_guide.md
Use dashes for lists
Remove leading spaces
Edit the language guidance section
=> Style guide clean up

Document/0x07c-Testing-Cryptography.md
=> A small typo fix

Document/0x07a-Testing-Authentication-and-Session-Management.md
One source to consider: https://www.blackhat.com/docs/eu-16/materials/eu-16-Yang-Signing-Into-Billion-Mobile-Apps-Effortlessly-With-OAuth20-wp.pdf
=> Secured place for "Testing OAuth2 implementation"

Document/0x05d-Testing-Data-Storage.md
Also offered an alternative approach based on commenting out log statements with Gradle.
#467
=> Added reference to an issue regarding log stripping with ProGuard.

Document/0x04d-Security-Testing-SDLC.md, Document/0x05a-Platform-Overview.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x07a-Testing-Authentication-and-Session-Management.md
=> Modify pages for inline references

Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04f-Testing-Network-Communication.md, Document/0x04g-Testing-Cryptography.md, Document/0x05d-Testing-Data-Storage.md, Document/0x05e-Testing-Cryptography.md, Document/0x05f-Testing-Local-Authentication.md, Document/0x05g-Testing-Network-Communication.md, Document/0x05h-Testing-Platform-Interaction.md, Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06f-Testing-Local-Authentication.md, Document/0x06g-Testing-Network-Communication.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Make them consistent according to the testcase template.
=> Update all references to MASVS

Document/0x05h-Testing-Platform-Interaction.md
And make the sentence a bit more concise.
=> Fix some typo's

Document/0x05f-Testing-Local-Authentication.md
Complete, pending a couple questions.
=> Edits for 0x05f complete

Document/0x05g-Testing-Network-Communication.md
Hello,
I have added information about SSL Pinning in the case of usage of:
* WebView
* Network Security Config feature of Android v7+
Thanks in advance
=> SSL Pinning for WebView and NSC

Document/0x06f-Testing-Local-Authentication.md
Added a link to keychain. Also, is it worth mentioning Secure Enclave?
=> Edits complete, question pending

Document/0x05d-Testing-Data-Storage.md
Not yet ready to be merged!
I will continue reviewing and editing this chapter in the next days.
I opened the PR for early access to the changes (feel free to comment) and coordination if anyone else is looking in the issue.
#478
=> Edited and extended the "Testing for sensitive data in memory" chapter.

Document/0x03-Overview.md
First round of edits with some questions/comments included.
=> Update 0x03-Overview.md - First round of edits with some questions/comments included.

Document/0x04e-Testing-Authentication-and-Session-Management.md
Images will not display as I don't have rights to upload them for now. However, all the rest of the section is in its final state.
=> 0x4e - Quick guide on dynamic analysis, Testing Excessive Login Attempts

Document/0x06a-Platform-Overview.md
App structure image <img src="/Images/Chapters/0x06a/iOS_Folder_Structure.png" width="500px"/> does not work - opening the link throws a PageNotFound error
=> 0x06a - App Structure - end - minor linguistic changes

Document/0x05h-Testing-Platform-Interaction.md
Hello,
I have added a mini procedure in order to help to statically identify code that can be used to detect if the device is rooted.
Thanks in advance.
=> Mini procedure to identify detection of rooted device

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
Hello,
I have added a mini procedure about attaching jdb to a PID in order to have a help about how setup the communication channel.
Thanks in advances.
=> Mini procedure about attaching jdb to a PID

Document/0x05a-Platform-Overview.md
=> 0x05a-Platform-Overview line 366 - 558

Document/0x05a-Platform-Overview.md
=> 0x05a-Platform-Overview line 252-366

Document/0x05a-Platform-Overview.md
=> 0x05a-Platform-Overview line 130 - 252

Document/0x05a-Platform-Overview.md
=> 0x05a-Platform-Overview line 30-130

Document/0x04g-Testing-Cryptography.md
More edits and structural changes may come after I understand certain parts better. First pass doesn't contain polished grammar/spelling, just trying to work on the rough content and structure
=> 1st round of edits and questions in Testing-Cryptography

Document/0x04b-Mobile-App-Security-Testing.md
Refactoring and removal of redundant content
=> 0x4b - Merge "security testing" and "sdlc" chapters

Document/0x08-Testing-Tools.md
Add objection to testing tools section.
=> Add objection

Document/0x05c-Reverse-Engineering-and-Tampering.md
Debugging with an IDE: added a few clarifications and extra steps.
=> Update 0x05c-Reverse-Engineering-and-Tampering.md - Debugging with an IDE

Document/0x05c-Reverse-Engineering-and-Tampering.md
Added an optimized approach to "The Android Debug Bridge" section, regarding breakpoint management during a debug session.
Fixed a few typos inside the debugging sections.
=> Update 0x05c-Reverse-Engineering-and-Tampering.md - The Android Debug Bridge

Crackmes/README.md
Level01 solution by David moved from Android to iOS
=> Level01 solution moved from Android to iOS

Document/0x05c-Reverse-Engineering-and-Tampering.md
Frida Stalker update.
Replaced one "ass" ;)
=> 0x05c-Reverse-Engineering-and-Tampering.md - Frida Stalker

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> 0x05c-Reverse-Engineering-and-Tampering.md - Frida

Document/0x04b-Mobile-App-Security-Testing.md
The removed section was appearing twice in the chapter. Therefore, one of the 2 sections has been removed.
=> 0x4b - Remove redundant content

Document/0x04h-Testing-Code-Quality.md
=> Typos in the testing code quality section

Document/0x08-Testing-Tools.md
Formatted the file `0x08-Testing-Tools.md` to resolve markdown mistakes.
=> Corrected some markdown link mistakes

Document/0x05b-Basic-Security_Testing.md
Adding commands that can be used to test vulnerable broadcast receivers.
=> Add broadcast info

Document/0x08-Testing-Tools.md
Adding Android Studio to the IDE's.
=> Add Android Studio

Document/0x04h-Testing-Code-Quality.md
Let me know if I need to make any further changes regarding format. 🎉
=> Adding an XSS example via start ContentActivity 

Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
App sandbox dirs updates and IPA installer references consistency.
=>  App sandbox dirs updates and IPA installer references 

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
Minor error corrections in 0x05j-Testing-Resiliency-Against-Reverse-Engineering.md.
=> Minor error corrections

Document/0x05c-Reverse-Engineering-and-Tampering.md
Hello,
I have added information about patching of a Android application developed with the React Native framework.
Thanks in advance :smiley:
=> Android with the React Native framework

Document/0x04e-Testing-Authentication-and-Session-Management.md
Set the link to -> https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java
=> Updated OWASP JWT Cheat Sheet Link

Document/0x05a-Platform-Overview.md
=> Updated mistake

Document/0x06c-Reverse-Engineering-and-Tampering.md
Hello,
I have added information about patching of a iOS application developed with the React Native framework.
Thanks in advance :smiley:
=> iOS with the React Native framework

Document/0x04b-Mobile-App-Security-Testing.md
Although wording could be improved, here is at least a fix for #898.
=> Fix for #898: added Terraform and Ansible

Document/0x06c-Reverse-Engineering-and-Tampering.md
Hey!
Thanks for this great book. I saw a small typo and a couple of things that didn't make sense in the script. I ran mine and it works without issues.
The issues I found:
- `NSLog(args[2].absoluteString_());` should not work. `args[2]` is a `NativePointer`
- Its better to include a try-finally when using autorelease pools
- `var URL = ObjC.classes.NSURLRequest["- initWithURL:];` contains an unterminated string
=> Fix Frida URL listener script

Document/0x08-Testing-Tools.md
This PR coveres issue #<insert number here>.
=> adding mobile hacking tools project

Document/0x06a-Platform-Overview.md
Your contribution is written in the 2nd person (e.g. you)
[x ] Your contribution is written in an active present form for as much as possible.
[x ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to Mitre/MASVS/etc. are up to date)
[x ] Your contribution has proper formatted markdown and/or code
[x ] Any references to website have been formatted as [TEXT](URL “NAME”)
[x ] You verified/tested the effectivnes of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)
This PR coveres issue …
=> Fixing #855

Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04h-Testing-Code-Quality.md, Document/0x05h-Testing-Platform-Interaction.md, Document/0x06h-Testing-Platform-Interaction.md
Based on a few regexes, I think I got them all :).
This PR covers issue #981 .
=> Fixed gitbook urls

Document/0x05h-Testing-Platform-Interaction.md
In order to fix fragment vulnerability, I've added the steps to check if the version of it is lower than 19.
=> added How to fix Fragment Injection vulnerability

Document/0x08-Testing-Tools.md
=> Fixed extra brackets in links

Document/0x09-Suggested-Reading.md
=> Added in the Android Internals book

Crackmes/README.md
Simple URL fix (anchor no longer worked)
=> Fix the URL for a crackme solution

README.md
=> removed old links

Document/0x05a-Platform-Overview.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
This PR covers the earlier issue of readers not being able to find the apksigner.
=> Clear instructions for where the apksigner is located

Document/0x08-Testing-Tools.md
=> Added overview of vulnerable apps which can still build

README.md
=> Twitter integration

Document/0x05f-Testing-Local-Authentication.md
This PR covers issue #1018.
(Some rewriting and a few typo's. I also changed lockscreen to lock screen)
=> QA on #1018 & lockscreen fix

Document/0x05a-Platform-Overview.md, Document/0x06a-Platform-Overview.md, Document/0x08-Testing-Tools.md
=> QA on 0x08 - Vulnerable applications

Document/0x05a-Platform-Overview.md, Document/0x06a-Platform-Overview.md
This PR covers issue #1023 
--
I've changed the perspective of the attack surface, since "Having unsafe input" is worded weirdly. Feel free to discuss :).
=> Qa for #1023

Document/0x04h-Testing-Code-Quality.md
=> Kotlin examples for 0x04h complete.

Document/0x09-Suggested-Reading.md
Added Android Internals by Jonathan Levin & Programming Linux anti-reversing techniques by Jacob Baines
=> Add two books to suggested reading

Document/0x05d-Testing-Data-Storage.md
=> Typo "extneral"

Document/0x02-Frontispiece.md
=> #1060: .jpg to .png

Document-ja/0x08-Testing-Tools.md
=> merge 'update testing tools 1066' into doc-ja/08-tools

Document/0x04g-Testing-Cryptography.md
=> fix OWASP Mobile Top 10 section of 0x04g

Document/0x05e-Testing-Cryptography.md, Document/0x05h-Testing-Platform-Interaction.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06d-Testing-Data-Storage.md, Document/0x06g-Testing-Network-Communication.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
=> #1074 fix OWASP Mobile Top 10 section

Document/0x05c-Reverse-Engineering-and-Tampering.md
Please have a look at the references. Should I add a references Section for them ? Should I rename them from 5 and 6 to 1 and 2 since they seem to be the only 2 references on this page.
This PR covers issue #1076.
=> #1076 - Update 0x05c regarding latest angr release

Document/0x06b-Basic-Security-Testing.md
=> Test Env section review

Document/0x06a-Platform-Overview.md
=> Overview general review

Document/0x06a-Platform-Overview.md
=> Overview iOS introduction review

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> For issue #963 (dangers of SMS as a second factor)

Document/0x06b-Basic-Security-Testing.md
pip install frida-tools is the correct one
=> Updated command line for installing fridra

Document/0x06d-Testing-Data-Storage.md
It's helpful to use keyboard_autocomplete module to analyze keyboard data
=> Added keyboard_autocomplete to dump keyboard

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
=> Change default port for Frida

Document/0x05a-Platform-Overview.md
=>  Typo Error in Line 346 of Android Platform Overview

Document/0x04f-Testing-Network-Communication.md
=> Recommended Cipher suites

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
=> fixed small reference issue with reverse engineering

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
=> Small re fixes for ios

Document/0x05b-Basic-Security_Testing.md, Document/0x05d-Testing-Data-Storage.md
This PR covers issue https://github.com/OWASP/owasp-mstg/issues/1068.
=> Security Libraries 

Document/0x05d-Testing-Data-Storage.md
- [] Your contribution is written in the 2nd person (e.g. you)
=> added references

Document/0x05g-Testing-Network-Communication.md, Document/0x06g-Testing-Network-Communication.md
=> Added small pinning examples

Document/0x05b-Basic-Security_Testing.md
=> Android updates in TLS stack starting at Android 8 and 9

Document/0x05b-Basic-Security_Testing.md, Document/0x05g-Testing-Network-Communication.md
=> #952: small reordering of additions

Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06g-Testing-Network-Communication.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
This PR is about some changes in code block headers so they have the proper code linting.
=> Change some code block headers to the proper language

Document/0x06b-Basic-Security-Testing.md
=> added iOS testing via USB

Document/0x05h-Testing-Platform-Interaction.md
=> Permissions changes in Android 8

Document/0x06b-Basic-Security-Testing.md
=> added reference list with tools #1137

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
=> #1057 - Extend safetyned attestation for Android

Document/0x02-Frontispiece.md, Tools/README.md
=> Update release proc

Document/0x06b-Basic-Security-Testing.md
=> Resolved Typo in 0x06b-Basic Security Testing 

style_guide.md
This PR covers issue #1166 .
Apparently this was already in the intro of the style guide ("When giving technical instructions, address the reader in the second person."), but I've added the examples from #1166 and added some more consistency in the title numbering.
=> Fixing 1166 (Style guide - test cases - active voice)

Document/0x05b-Basic-Security_Testing.md
=> First draft for issue #892 - Obfuscated SSL pinning

Document/0x08-Testing-Tools.md
Added Ghidra, Binary ninja and Retdec to the list.
=> Add RE tools to Testing Tools

Document/0x02-Frontispiece.md
=> updated Acknowledgments/Co-Authors

Document/0x06h-Testing-Platform-Interaction.md
=> #1184: Added missing items for 0x6h

Document-ja/0x09-Suggested-Reading.md
=> merge 'Add two books to suggested reading' into doc-ja/09-reading

CHANGELOG.md
This PR corrects typos and punctuation in changelog.
=> typos and punctuation corrected in changelog

Document/CHANGELOG.md
This PR corrects typos and punctuation in Document/changelog.
=> typos and punctuation corrected in Document/changelog

README.md, Tools/README.md, Tools/gendocsLocal.sh
=> Some more identification/readme updates, etc

Document/0x02-Frontispiece.md, README.md
=> Added ISBN

Document/0x03-Overview.md
Changed "mobile app penetration testing tools" to "mobile app penetration testers".
=> Updated key areas section

Document/0x06a-Platform-Overview.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
=> first draft of restructuring iOS basic testing

Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md
Fix markdown issues for 0x05b and 0x05c. Master is now error free.
=> Fix markdown

Document/0x04a-Mobile-App-Taxonomy.md, Tools/Apply_Link_Check.sh, Tools/Apply_Linter_Check.sh, Tools/gendocs.sh
This PR improves the feedback provided by the system for those who have write access to the repo.
=> less_noise: attempt to make feedback a little cleaner

Document/0x06b-Basic-Security-Testing.md, Document/0x06h-Testing-Platform-Interaction.md
=> Acquiring the app binary to 0x06b + minor typo corrections

Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
=> issue 1242 Xcode setup

.gitignore, CONTRIBUTING.md, README.md
=> Simplified readme, updated CONTRIBUTING.md

Document/0x06d-Testing-Data-Storage.md
=> iOS Backup 

Document/0x06b-Basic-Security-Testing.md
=> last updates

Document/0x04h-Testing-Code-Quality.md
=> removed yahoo weather exploit desc and linked to blog instead

Document/0x05b-Basic-Security_Testing.md
=> 0x05b drozer reviewed

CONTRIBUTING.md
=> Updates markdown numbering issue in the contributing.md

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
=> modified jb details

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md
=> Simple device binding additions

Document/0x05b-Basic-Security_Testing.md, Document/0x06b-Basic-Security-Testing.md
=> (WIP) Recommended Tools - objection

Document/0x05b-Basic-Security_Testing.md
Small PR to make it more compact and keep it consistent with other tools.
=> Fix drozer commands for consistency

Document/0x05b-Basic-Security_Testing.md
=> R2frida documentation for 0x05b

Document/0x06b-Basic-Security-Testing.md
=> frida-ios-dump to extract ipa

Document/0x06b-Basic-Security-Testing.md
=> network fix and title fix

Document/0x02-Frontispiece.md
=> Update the co-author section

Document/0x06b-Basic-Security-Testing.md
finalising the iOS basic security testing chapter
=> finished 0x06b

Document/0x02-Frontispiece.md, Document/Users.md, README.md, Users.md
=> #1046: First iteration of using companies and standards

Document/0x05b-Basic-Security_Testing.md
Added an intro to r2, installation instructions references for installing on systems and actual android devices, and basic commands for android analysis.
This PR covers issue #1231.
=> Radare2 - #1231

Users.md
=> Added Toreon as per request from Xpl0SIV3

Document/0x06b-Basic-Security-Testing.md
This PR covers issue #1164 
NOTE: first review and merge #1319 !
=> #1146: first attempt to fix/note usb locking

Document/0x06b-Basic-Security-Testing.md
Changed macOS device to Host computer in the title so we can also put it in the Android chapter as "#### Recommended Tools - Host Computer". Also because it is not 100% required but recommended. We don't need a mac to run Frida, objection (to the device, not patching), Ghidra, burp, etc.
=> Title changed - removed macOS and put Host Computer instead

Document/0x02-Frontispiece.md
=> Correct spelling of a surname

CHANGELOG.md, Document/0x04h-Testing-Code-Quality.md, Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
=> Release notes 113 oss

CHANGELOG.md
=> Fixed feedback on release-notes

.markdownlint.json, Document/0x02-Frontispiece.md, Document/0x03-Overview.md, Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04f-Testing-Network-Communication.md, Document/0x04g-Testing-Cryptography.md, Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md, Document/0x05h-Testing-Platform-Interaction.md
=> #1398: fix pagebreaks pdf

Users.md
=> added TRAFICOM

Document/0x06b-Basic-Security-Testing.md
=> chimera needle

Checklists/README.md
=> Update README.md with image again

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> 1321 password update

Users.md
=> Updated with Vertical Structure

Users.md
=> Added the organisation "Lucideus Inc."

Users.md
=> Adding 7asecurity

Document/0x06d-Testing-Data-Storage.md, Document/0x06e-Testing-Cryptography.md, Document/0x06f-Testing-Local-Authentication.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Updating code samples to Swift 5. 
This PR covers issue #961
=> Swift 5 updates

Document/0x02-Frontispiece.md
=> Updated contributors (added Caleb

Document/0x03-Overview.md
0x04-General-Testing-Guide.md => 0x04a-General-Testing-Guide.md
=> fix bad Navigating at the end of 0x03-Overview.md

Document/0x05d-Testing-Data-Storage.md
=> Fixed word usage

Document/0x05d-Testing-Data-Storage.md
=> Removed extra word, formatting

Checklists/README.md
This PR covers issue #1429.
Points tackled in this PR:
- File hashes
- Methods to generate the hashes on every system
This doesn't fully cover the issue mentioned.
=> Feat: Excel Hashes and Methods to Generate Them

Document/0x08-Testing-Tools.md
=> small fixes in androgoat description

CONTRIBUTING.md
- Increase readability and scannability 
- Fixed minor typos/format issues
- Added reference to Code of Conduct
=> Review contributing

README.md
=> #1459: fix links to google docs in readme

README.md
updated readme.md with the new slack link
=> updated readme.md with the new slack link

Document/0x06b-Basic-Security-Testing.md
=> Small layout fix

Document/0x06e-Testing-Cryptography.md
Add [Apple CryptoKit](https://developer.apple.com/documentation/cryptokit/)
This PR covers issue #1317 and #961.
=> Add Apple CryptoKit

Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x05a-Platform-Overview.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md, Document/0x08-Testing-Tools.md, Tools/Apply_Linter_Check.sh
=> Fix for all udid alternatives and linter check

Document/0x06c-Reverse-Engineering-and-Tampering.md
=> Fixed Linting Errors and Style Guide Compliance in 06c

Document/0x06c-Reverse-Engineering-and-Tampering.md
They are just minor issues. Thank you for great readings.
=> Fix dead links due to case sensitive urls

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> Fixed grammar

Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
=> #1518: fix for erroneous v3 signing availaiblity ATM

Users.md
Added STM Solutions to Users.md 
STM Solutions actively uses both guides (MASVS and MSTG) during pentests.
This PR covers issue #1528
=> Added STM Solutions to Users.md

Document/0x02-Frontispiece.md
First automated update of frontispiece
=> Updated frontispiece

Users.md
=> Added new company to Users.md

Document/0x02-Frontispiece.md
=> Added first donator according to new policies

Document/0x02-Frontispiece.md
=> Added eShard

Document/0x02-Frontispiece.md
=> added Bay Area

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> #1556: fix JWT description

Document/0x06b-Basic-Security-Testing.md
=> updated appsync repo

Document/0x05b-Basic-Security_Testing.md
=> added house - Android tool

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> #1560: updated sentences to be more clear

Document/0x02-Frontispiece.md
=> Added MAxim as co-author

Document/0x04f-Testing-Network-Communication.md, Document/0x04h-Testing-Code-Quality.md
=> #1565 fix: CA install link parsing

Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05g-Testing-Network-Communication.md, Document/0x06b-Basic-Security-Testing.md
This PR fixes a few broken links, that were identified by "Apply_Link_Check.sh". 
=> fixed broken links, MWR etc.

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> added MFA on remote endpoint

CODE_OF_CONDUCT.md, Document/0x02-Frontispiece.md
We have no disclaimer yet, this is a first draft to create one.
=> Disclaimer

Document/0x00-Header.md, Document/0x03-Overview.md, Document/0x04b-Mobile-App-Security-Testing.md, Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x04f-Testing-Network-Communication.md, Document/0x04g-Testing-Cryptography.md, Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05d-Testing-Data-Storage.md, Document/0x05e-Testing-Cryptography.md, Document/0x05h-Testing-Platform-Interaction.md, Document/0x05i-Testing-Code-Quality-and-Build-Settings.md, Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
This PR is doing a QA of all pictures. Some pictures were not showing due to wrong filename/path, some pictures were still too big/small and all pictures are now using an image tag.
This PR covers issue #1156 .
=> updated all links to img tag

Document/0x05c-Reverse-Engineering-and-Tampering.md
Remove additional "Android" word typo.
Sorry @sushi2k, 
It appears there was a typo in my #1579 PR.
=> Remove accidental "Android" word

Crackmes/README.md
Thanks @su-vikas for the solution! Nice writeup
=> added iOS crackme2 writeup

Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
For issue #1373
Added content for iOS emulation-based analysis section.
=> ios emulation-based analysis 

Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06c-Reverse-Engineering-and-Tampering.md
=> remove expensive

style_guide.md
=> Added suggestions for gender neutrality

Document/0x06c-Reverse-Engineering-and-Tampering.md
Issue #1376 
Added content for Information Gathering using Frida for an iOS application.
=> 6c information gathering

Document/0x05b-Basic-Security_Testing.md
=> removed picture caption leftover

Document/0x05b-Basic-Security_Testing.md
=> fixed header

Document-ja/0x08-Testing-Tools.md, Document/0x03-Overview.md, Document/0x04f-Testing-Network-Communication.md, Document/0x05b-Basic-Security_Testing.md, Document/0x08-Testing-Tools.md, style_guide.md
=> WiFi to Wi-Fi

Document/0x02-Frontispiece.md
=> Updated contributor list

Document/0x05c-Reverse-Engineering-and-Tampering.md
For Issue #1364 
added content for information gathering using Frida. Another low hanging one, lets get it out of way :)
=> added content to information gathering using frida

Document/0x05c-Reverse-Engineering-and-Tampering.md
For issue #1359 
Added basic information gathering section for Android.
=> 5c basic information gathering

Document/0x05g-Testing-Network-Communication.md
=> Adding missing space

Document/0x04c-Tampering-and-Reverse-Engineering.md, Document/0x04e-Testing-Authentication-and-Session-Management.md, Document/0x05a-Platform-Overview.md, Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05g-Testing-Network-Communication.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06d-Testing-Data-Storage.md, Document/0x06h-Testing-Platform-Interaction.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
=> Adding an example with truststore to bypass cert pinning

Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md, Document/0x05d-Testing-Data-Storage.md, Document/0x05h-Testing-Platform-Interaction.md
=> Unifing convent provider convention

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> fixed typo

Document/0x02-Frontispiece.md, README.md
=> Fixed Slack Links

Document/0x02-Frontispiece.md
=> Maxim author

Document/0x04f-Testing-Network-Communication.md, Document/0x05e-Testing-Cryptography.md
=> Android 10 TLS and cryptography updates

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Fix Wait for Debugger reference

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Removed hostname from code snippet

Document/0x05h-Testing-Platform-Interaction.md
Updated section to make it more actual; content a bit simplified and added a more direct explanation of the security risk and some considerations on the static analysis.
=> updated javascript bridges

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Document Improved

README.md
This PR closes #877.
I hope we can finally close this once and for all ;-)
=> Update README.md with new Slack URL 

Document/0x08-Testing-Tools.md
=> Added UnSAFE Bank iOS Application

Document/0x02-Frontispiece.md
We have a new co-author! Thank you very much @su-vikas for the hard work and congratulations 👏
=> Added Vikas as Co-author

Document/0x02-Frontispiece.md
https://github.com/OWASP/owasp-masvs/issues/405
=> fixed slack invite

Document/0x06c-Reverse-Engineering-and-Tampering.md
The PR is related to a discussion on Slack with @commjoen
=> Add the procedure to sign the debugserver for iOS 12 and higher

Document/0x05b-Basic-Security_Testing.md
=> added fix for '/system' not in /proc/mounts

Document/0x06g-Testing-Network-Communication.md
Added an introduction to Network.framework and URLSession, included example code of Network.framework to fetch https://owasp.org. 
This PR is related to #1160
=> Add Network.framework introduction

Document/0x05d-Testing-Data-Storage.md
This PR closes #1666.
Not sure about grammar, check please.
=> Snapshots folder android #1666

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
=> Added getppid as debugger detection

Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md
Fixed a typo,
Made first letter of class names uppercase,
Slightly changed services sub title.
=> Minor updates for 0x05a-Platform-Overview.md

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Added [Swift Package Manager](https://swift.org/package-manager/), OWASP Dependency-Check for CocoaPods and added minor edits and linting. 
- [X ] Your contribution is written in the 2nd person (e.g. you)
- [X ] Your contribution is written in an active present form for as much as possible.
- [X ] Your contribution has proper formatted markdown and/or code
- [X ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [X ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)
This PR closes #< insert number here …
=> Add Swift PM and Dependency-check

Document/0x05b-Basic-Security_Testing.md, Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Small fixes

Document/0x02-Frontispiece.md
=> Updated contributors:

Document/0x05h-Testing-Platform-Interaction.md
Deleted a repeating paragraph.
=> Deleted repeating paragraph

Crackmes/README.md
It could be better to use gitbook links?
=> Fix crackme solution links

Document/0x05b-Basic-Security_Testing.md
Added the content regarding the enumeration of domain names from the APK file. I have also included APKEnum python utility which helps us automate this.
=> Added APK Content For APK Domain Enumeration

Document/0x02-Frontispiece.md
=> updated contributors

Tools/README.md
=> small updates to the release process

.travis.yml, Document/0x02-Frontispiece.md, Document/CHANGELOG.md, Tools/README.md
=> Release 1.2

.travis.yml, Tools/README.md, Tools/before_install.sh, Tools/gendocs.sh
=> Simplifyrelease

.travis.yml, Tools/gendocs.sh
=> Hack for travis (As decomm is incoming)

.travis.yml
=> travis wait update

Document/0x06h-Testing-Platform-Interaction.md
- Fixes WebViwes typo. 
P.S. Thank you for the amazing resources
=> Fix WebViwes typo

Document/0x05b-Basic-Security_Testing.md
Added clikable links for Tampering and Reverse Engineering on Android references and mentioned radare2 official book at the end of radare2 section.
=> added hyperlinks for titles and radare2 book

Document/0x06b-Basic-Security-Testing.md
added links for references in the document and fixed a typo.
=> added links for references in the document

Document/0x05f-Testing-Local-Authentication.md
=> Fixed typoe in "cryptObject"

README.md
=> updated status badges

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06c-Reverse-Engineering-and-Tampering.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x09-Suggested-Reading.md, Users.md
=> Fix Dead Links

.github/workflows/config/mlc_config.json
=> added last cydia repo to exclusion list

.github/workflows/checkLinks.yml, .github/workflows/config/mlc_config.json, Document/0x05h-Testing-Platform-Interaction.md
=> added more ignores

.github/workflows/docgenerator.yml, .github/workflows/release.yml, tools/docker/README.md, tools/docker/run_docker_mstg_generation_on_local.sh
=> updated to docker v0.3 image

Document/0x05c-Reverse-Engineering-and-Tampering.md
smalidea has been split out into its own repository. updated its url.
=> updated smalidea links

README.md
=> updated readme instructions to new buildsystem

Users.md
=> Add stingray

tools/docker/pandoc_makedocs.sh
This reduces the overflows and highly improves readability of all code blocks in the PDF
=> Fixed readability of code blocks

Document/0x05d-Testing-Data-Storage.md
- [ x] Your contribution is written in the 2nd person (e.g. you)
- [ x] Your contribution is written in an active present form for as much as possible.
- [ x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ x] Your contribution has proper formatted markdown and/or code
- [ x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)
This …
=> Adding Kotlin examples and one Dart example to 0x05d

Document/0x05a-Platform-Overview.md
This PR add progress to #962 .
=> Adding Kotlin examples to 0x05a

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
---
Besides this, I found dead link "The Jiu-Jitsu of Detecting Frida" in 0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, but I couldn't find correct URL.
=> Fix typo and links

Document/0x02-Frontispiece.md
Hi guys, just changing from a nickname to actual name.
=> NameChanging

Document/0x05a-Platform-Overview.md
Small correction to build a complete sentence.
=> Update wording on 0x05a-Platform-Overview.md

CONTRIBUTING.md
=> Add Disclaimer to CONTRIBUTING.md

Document/0x05a-Platform-Overview.md, Document/0x05b-Basic-Security_Testing.md
=> Remove Pagebreak Annotations

CODE_OF_CONDUCT.md, Users.md
=> Cleanup jeroen

Document/0x02-Frontispiece.md, README.md
=> fix slack link

README.md, Users.md
=> Removed Jeroen from points of contact

Document/0x05c-Reverse-Engineering-and-Tampering.md, Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06b-Basic-Security-Testing.md, Document/0x06i-Testing-Code-Quality-and-Build-Settings.md, Document/0x08-Testing-Tools.md
This PR:
- closes #1794
- closes #1781
- closes #1784
- closes #1725
- closes #1697
=> Various fixes

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
=> fix(typo): Update 0x06i-Testing-Code-Quality-and-Build-Settings.md

Crackmes/README.md
Solving OWASP UnCrackable Android App Level 1 and 2 with Runtime Mobile Security (RMS) - VIDEOs
=> Android solutions with RMS

Document/0x06d-Testing-Data-Storage.md
=> Add Cache.db description and recommendations

Document/0x02-Frontispiece.md
=> Update Top Contributors

Document/0x05h-Testing-Platform-Interaction.md
correct typo in Testing-Platform-Interaction
=> correct typo in Testing-Platform-Interaction

Document/0x05h-Testing-Platform-Interaction.md
* Limit size is 15MB now
* https://developer.android.com/topic/google-play-instant/tech-requirements#total-download-size
* OS version may be typo
* https://developer.android.com/topic/google-play-instant/overview#how-it-works
=> update Google Play Instant info

Document/0x08-Testing-Tools.md
to be merged instead of #1855 due to inactivity and different location of content.
=> added changes from 1855

Document/0x01-Foreword.md
=> Fixed a typo in foreword

Document/0x06d-Testing-Data-Storage.md
Hi,
This PR add information about how to identify if a backup is encrypted or not.
The LINKS checker failed, however, i did not add any links, so, I dit not have broken something with my PR I think 😄 
Thanks a lot in advance 😃
=> Add how to identify if a backup is encrypted

Document/0x06d-Testing-Data-Storage.md, Document/0x08-Testing-Tools.md
Hi,
This PR add the reference to the tool [iOSbackup](https://github.com/avibrazil/iOSbackup).
This PR closes #1879 .
I have explicitly not added code sample because:
1. There are already plenty of code sample on the README of the github repo of the tool.
2. It made the reference in MSTG more resilient against evolution of the referenced tool in terms of parameters/calls changes.
Failure in the LINKS check were not due to the links I added.
Feel free to ping me if change are needed 😃 
Thanks a lot in advance 😃
=> Add reference to the tool iOSbackup

Crackmes/README.md
=> Adding contribution to the Crackme Write-ups: UnCrackable Level 1

Crackmes/README.md
=> Added iOS crackmes solutions by Pietro Oliva

Crackmes/README.md
=> Adding contribution to the Crackme Write-ups: UnCrackable Level 2

style_guide.md
=> Update style_guide.md regarding Markdown Link Titles

Document/0x05b-Basic-Security_Testing.md, Document/0x08-Testing-Tools.md
Hi,
This PR closes #1898 
Thanks a lot in advance 😃
=> Add tool SCRCPY

Document/0x06d-Testing-Data-Storage.md, Document/0x06h-Testing-Platform-Interaction.md
Hi,
PR is linked to the issue #1839  .
ℹ️ It do not entirelly addess the issue because work on Drozer is more larger and must be provided in additional PRs.
=> [iOS] Remove any reference to NEEDLE tool.

Document/0x04b-Mobile-App-Security-Testing.md
=> Remove a duplicate

Crackmes/README.md
=> [Crackme] Added Android solutions for level 1, 2 and 3

Document/0x06d-Testing-Data-Storage.md
- restructured whole test case to better match the new approach
- removed ObjC code
=> Update screenshots section for iOS

Document/0x05h-Testing-Platform-Interaction.md
In the exploit.apk, the code is, i.setData(Uri.parse("https://security.claudio.pt")); not Intent intent = xxx
=> Wrong exploit on Testing for Fragment Injection

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Sorry that I don't really understand the meaning of some checks in the list so I didn't mark them checked.
=> Update dated/broken links in the docs

tools/Apply_Link_Check.sh
Took some time to figure out how to do this locally. but also this fix will match github action results so people dont get bogus errors.
=> linking to right check file

.github/workflows/docgenerator.yml
=> get latest tag from tags and not from releases

Document/0x04a-Mobile-App-Taxonomy.md
=> Remove title from link

Document/0x04e-Testing-Authentication-and-Session-Management.md
The "link above" was an article referred in the owasp cheat sheet
=> there is no "link above"

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
Add link to latest code signature format and "static analysis" title.
=> Add link to latest code signature format

Document/0x04g-Testing-Cryptography.md
Fix the outline of the 4g chapter (no changes in the content itself).
=> Fix chapter outline for 0x04g (Mobile App Cryptography)

.github/release.yml
Updated Changelog Automation according to the new MSTG architecture.
=> Update Changelog Automation

.github/workflows/codespell.yml
=> GitHub Action for codespell

Crackmes/README.md, Document/0x05c-Reverse-Engineering-and-Tampering.md
Angr exploit updated. It now works with Angr 9.2.1 correctly.
=> 0x05c - Update Angr Example

Document/0x04i-Testing-User-Privacy-Protection.md
came after watching the OWASP Tunisia Chapter livestream
=> Fixed Typos in 0x04i-Testing-User-Privacy-Protection

Document/0x02b-MASVS-MSTG-Adoption.md
Fixes the table widths on the adoption page.
=> Fix adoption table widths

Document/0x05a-Platform-Overview.md, Document/0x05e-Testing-Cryptography.md, Document/0x05h-Testing-Platform-Interaction.md
"soft" update on API changes. We'll address this a bit better in the future.
=> Add New References to Android API changes (by @NowSecure)

Document/0x04f-Testing-Network-Communication.md
=> Fix typo in 0x04f-Testing-Network-Communication.md

docs/contributing/1_How_Can_You_Contribute.md
=> Resolved broken link to OWASP MASTG authors and co-authors (#2197) ;

docs/contributing/1_How_Can_You_Contribute.md
=> Resolved broken link to OWASP MASTG Contributors (#2199) ;

Document/0x02a-Frontispiece.md, README.md, docs/contributing/1_How_Can_You_Contribute.md, docs/news.md, tools/README.md
=> Fix lulu.com links

tools/scripts/transform_links.py
Relative links must remain relative
=> Fix link transform

Document/0x04b-Mobile-App-Security-Testing.md, Document/0x04g-Testing-Cryptography.md, Document/0x06c-Reverse-Engineering-and-Tampering.md, Document/0x06f-Testing-Local-Authentication.md, Document/0x07-Appendix.md, tools/scripts/yaml_to_excel.py
=> Remove Appendix and N/A from Checklists

.github/workflows/docgenerator.yml
Thanks for the tip 
https://owasp.slack.com/archives/C0528SEKX/p1662724769280519
=> Restrict GITHUB_TOKEN permissions

.github/workflows/build-website.yml
fixing the pipeline for web deploy
=> fix sed commands

docs/contributing/5_Style_Guide.md
=> Add tech writing training to style guide #2007

.github/workflows/build-website.yml, mkdocs.yml, tools/scripts/structure_mastg.sh, tools/scripts/transform_files.py
=> Fix transform script to set correct links

docs/contributing.md
=> Fix broken emoji links

mkdocs.yml
Simple change to accommodate https://github.com/OWASP/owasp-mastg/issues/2260
This PR closes #2260
=> Update nav bar

docs/crackmes.md
Added links to the crackme's titles and added (easy) and (hard) to distinguish between the two L4 ones.
=> Update links for crackmes page

Document/0x08b-Reference-Apps.md
=> Proofreading fixes 0x08b-Reference-Apps.md

Document/0x05a-Platform-Overview.md
=> Proofreading fixes part 1 0x05a-Platform-Overview.md

mkdocs.yml
=> remove feat: suggest hightlight

Document/0x05b-Basic-Security_Testing.md
=> Proofreading fixes part 3 5x05b Basic Security Testing

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Proofreading fixes part 1 0x05c

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Proofreading fixes part 2 0x05c

Document/0x05c-Reverse-Engineering-and-Tampering.md
Small typo for sentence coherence
=> Proofreading fixes part 4 0x05c

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Proofreading fixes part 5 5x05c

docs/MAS_checklist.md
Fix download link of the Russian MAS Checklist.
Before it was pointing to the Korean version of the document.
=> Fix download link of the Russian MAS Checklist

Document/0x05c-Reverse-Engineering-and-Tampering.md
=> Proofreading fixes part 8 0x05c

Document/0x05d-Testing-Data-Storage.md
=> Proofreading fixes 0x05d part 2

Document/0x06i-Testing-Code-Quality-and-Build-Settings.md
=> Add otool command to 0x06i-Testing-Code-Quality-and-Build-Settings.md

Document/0x06c-Reverse-Engineering-and-Tampering.md
=> Fix Broken Link in 0x06c-Reverse-Engineering-and-Tampering.md

Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md, Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
=> [Phase 1] Android Resilicene chapter, theory moved up

Document/0x04f-Testing-Network-Communication.md, Document/0x05g-Testing-Network-Communication.md, Document/0x06g-Testing-Network-Communication.md
This PR closes #2223 and #2216 .
=> [Phase 1] Refactor Testing-Network-Communication.md

Document/0x05d-Testing-Data-Storage.md, Document/0x06d-Testing-Data-Storage.md
This PR closes #2220 and #2213.
=> [Phase 1] Refactor Testing-Data-Storage.md

docs/MASVS.md
=> Fix typo MASVS.md

tools/scripts/yaml_to_excel.py
Closes https://github.com/OWASP/owasp-mastg/issues/2415 (part 2)
=> Fix status validation for MASVS controls in checklist

docs/crackmes/Android.md
**Added solution for Android UnCrackable L1 using Mobile Security Framework(MobSF).**
=> UnCrackable L1 Solution using MobSF

about_cookies.md, mkdocs.yml
Add about cookies page and link in footer.
=> add about cookies

docs/assets/data/talks.yaml
=> New Talk: "OWASP MAS Project Showcase" @ OWASP AppSec US 2023

Document/0x02c-Acknowledgements.md
Our focus with the program are "consistent high-impact contributions". With this change we highlight that in our guidelines.
=> Update MAS Advocate guidelines

tests/android/MASVS-CRYPTO/MASTG-TEST-0013.md
Fixed broken hyperlink to the jadx tool page on line 33
=> Fixed broken hyperlink to the jadx tool page

Document/0x04e-Testing-Authentication-and-Session-Management.md
=> Changed incorrect reference to 'Resource Owner' to 'Resource Server'

.github/labeler.yml, docs/MASVS/index.md, docs/news.md, mkdocs.yml
Add MASVS-PRIVACY, update NEWS, MASVS page and mkdocs.yaml
=> Add MASVS v2.1.0 including MASVS-PRIVACY

Document/0x04i-Testing-User-Privacy-Protection.md
This is an edit of the Mobile App User Privacy document by technical writer Rob Thornton. It tightens up the writing without significantly changing the document.
=> Proofreading fixes 0x04i Testing-User-Privacy-Protection.md

Document/0x03-Overview.md, Document/0x04a-Mobile-App-Taxonomy.md
=> Technical Writer: made changes to enhance clarity - section in 0x04 ("guide") moved to 0x03

tests/ios/MASVS-STORAGE/MASTG-TEST-0052.md
=> Proofreading fix on MASTG-TEST-0052.md -> Testing Local Data Storage ( by @appknox )

.github/workflows/docgenerator.yml
=> fix upload artifact

Document/0x02b-MASVS-MASTG-Adoption.md
Product Development Cybersecurity Handbook: Concepts and Considerations for IoT Product Manufacturers
See https://csrc.nist.gov/pubs/cswp/33/product-development-cybersecurity-handbook/ipd
**Abstract:** _As interest in Internet of Things (IoT) technologies has grown, so have concerns and attention to cybersecurity of the newly network-connected products and services offered in many sectors, including energy services, water/waste-water services, automobiles, consumer electronics, and government. This Product Development Cybersecurity Handbook will describe concepts important to developing and deploying secure IoT products for any sector or use case, including discussion of IoT Product architecture, deployment, roles and cybersecurity perspectives. This publication extends and elaborates on …
=> Add NIST CSWP 33

tools/ios/MASTG-TOOL-0066.md
updated ssl-kill-switch to a newer version https://github.com/NyaMisty/ssl-kill-switch3
=> updated ssl-kill-switch from v2 to v3 (by @appknox)

mkdocs.yml
Updated copyright from 2023 to 2024 to match ongoing year.
=> Updated copyright from 2023 to 2024

tests/android/MASVS-CODE/MASTG-TEST-0025.md, tests/android/MASVS-NETWORK/MASTG-TEST-0019.md, tests/android/MASVS-NETWORK/MASTG-TEST-0022.md, tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md, tests/ios/MASVS-NETWORK/MASTG-TEST-0065.md, tests/ios/MASVS-NETWORK/MASTG-TEST-0068.md, tests/ios/MASVS-PLATFORM/MASTG-TEST-0070.md, tests/ios/MASVS-PLATFORM/MASTG-TEST-0071.md
=> Fix broken MASTG-TEST links

.github/workflows/spell-checker-pr.yml, .github/workflows/spell-checker.yml, techniques/ios/MASTG-TECH-0084.md, techniques/ios/MASTG-TECH-0092.md, tests/ios/MASVS-RESILIENCE/MASTG-TEST-0081.md, tests/ios/MASVS-RESILIENCE/MASTG-TEST-0082.md, tools/ios/MASTG-TOOL-0101.md
=> Add codesign

techniques/android/MASTG-TECH-0044.md, techniques/android/MASTG-TECH-0045.md, techniques/ios/MASTG-TECH-0096.md, techniques/ios/MASTG-TECH-0097.md, tools/generic/MASTG-TOOL-0036.md
=> Update r2frida examples using '\' instead of the current `:`

apps/android/MASTG-APP-0016.md
=> Add the vulnerable Android app "Finstergram"

.gitignore, docs/hooks/replace_snippets.py, docs/hooks/update_titles.py, mkdocs.yml, risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-insecure-random-use/demo-1/demo.md, risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/demo-1/demo.md, risks/MASVS-PRIVACY/1-data-minimization/sensitive-data-in-network-traffic/android-data-in-traffic-capture/demo-1/demo.md, risks/MASVS-STORAGE/2-prevent-data-leakage/data-in-logs/android-data-in-logs-frida/demo-1/demo.md, run_web.sh, src/scripts/structure_mastg.sh
Add support for snippets and tabs.
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
=> Enable snippets and tabs

techniques/android/MASTG-TECH-0005.md
=> Expand `adb install` technique

docs/hooks/add-cross-references.py, docs/stylesheets/extra.css, mkdocs.yml, run_web.sh, src/scripts/generate_cross_references.py
Closes #2786
Add cross-referencing for weaknesses, tests, and demos.
* **New Script**: Add `src/scripts/generate_cross_references.py` to generate a YAML file with cross-referencing information.
* **New Hook**: Add `docs/hooks/add-cross-references.py` to use the generated YAML and add relevant cross-referencing to each component's metadata.
* **Configuration**: Update `mkdocs.yml` to configure the new hook `docs/hooks/add-cross-references.py`.
* **Run Script**: Update `run_web.sh` to include a command to run the new script `src/scripts/generate_cross_references.py`.
=> Add cross-referencing for weaknesses, tests and demos

.github/workflows/build-website.yml
Enable Cross References for weaknesses, v2 tests and demos
=> Enable Cross References

tests/android/MASVS-CODE/MASTG-TEST-0034.md
=> [MASTG-TEST-0034] Fix typo in Overview section

src/scripts/populate_dynamic_pages.py
Closes #2804
Merge overview tables for `tests/index.md`, `tools/index.md`, `techniques/index.md`, and `apps/index.md` into a single table per file.
=> Merge tables in tests, tools, techniques

.github/workflows/docgenerator.yml, src/scripts/structure_masvs.sh
=> Fix GitHub build?

.github/workflows/docgenerator.yml, src/scripts/structure_masvs.sh
=> Fix GitHub build

tools/android/MASTG-TOOL-0103.md
=> [MASTG-TOOL-0103] add uber-apk-signer

docs/contributing/5_Style_Guide.md
=> Style guide fixes

.devcontainer/devcontainer.json, .dockerignore, Dockerfile, run_web.sh, src/scripts/structure_masvs.sh
Closes #2811
Add a Dockerfile to run the website locally exactly as it is done on the remote with our GitHub action.
=> Add Dockerfile to run website locally

tools/generic/MASTG-TOOL-0100.md
The tool is called reFlutter and not re-flutter.
=> [MASTG-TOOL-0100] Update tool name to reFlutter

.github/workflows/build-android-demos.yml
Restrict the demos action to changes in the `demos/` folder.
=> Limit demos action to changes in demos folder

docs/assets/data/talks.yaml
Add new talk to `docs/assets/data/talks.yaml`.
=> Add new talk at OWASP Atlanta Chapter 

weaknesses/MASVS-NETWORK/MASWE-0050.md, weaknesses/MASVS-NETWORK/MASWE-0052.md
=> Fix CWE ids to be just numbers

weaknesses/MASVS-NETWORK/MASWE-0052.md
=> Update MASWE-0052 draft

weaknesses/MASVS-AUTH/MASWE-0040.md
=> Update MASWE-0040.md with new links

weaknesses/MASVS-RESILIENCE/MASWE-0100.md
=> Update MASWE-0100 refs

tests/android/MASVS-RESILIENCE/MASTG-TEST-0038.md
=> Update MASTG-TEST-0038 to include new recommendations and v4

techniques/android/MASTG-TECH-0109.md
=> Changed the HTTP Toolkit link from pidcat to that

tests/android/MASVS-PLATFORM/MASTG-TEST-0028.md
=> Fix broken links in MASTG-TEST-0028

tests/android/MASVS-NETWORK/MASTG-TEST-0023.md
Some testers might find frida more convenient.
=> Add Frida replacing xposed to MASTG-TEST-0023

docs/hooks/create_dynamic_tables.py
deprecated was not showing properly in the MASWE table.
=> fix display of deprecated

techniques/ios/MASTG-TECH-0113.md, techniques/ios/MASTG-TECH-0114.md, tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0219.md, tests-beta/ios/MASVS-RESILIENCE/MASTG-TEST-0x83.md, tests/ios/MASVS-RESILIENCE/MASTG-TEST-0083.md, tools/ios/MASTG-TOOL-0121.md, tools/ios/MASTG-TOOL-0122.md
=> Port MASTG-TEST-0083 (by @guardsquare)

src/scripts/structure_masvs.sh
Thanks to @trufae for reporting this
=> Fix images paths in Update structure_masvs.sh

Document/0x05h-Testing-Platform-Interaction.md
Added 14 permissions:
android.permission.THREAD_NETWORK_PRIVILEGED
android.permission.RECORD_SENSITIVE_CONTENT
android.permission.RECEIVE_SENSITIVE_NOTIFICATIONS android.permission.WRITE_VERIFICATION_STATE_E2EE_CONTACT_KEYS android.permission.READ_DROPBOX_DATA
android.permission.WRITE_FLAGS
android.permission.REPORT_USAGE_STATS
android.permission.MANAGE_DISPLAYS
android.permission.RESTRICT_DISPLAY_MODES
android.permission.ACCESS_HIDDEN_PROFILES_FULL
android.permission.GET_BACKGROUND_INSTALLED_PACKAGES android.permission.REGISTER_NSD_OFFLOAD_ENGINE
android.permission.ACCESS_LAST_KNOWN_CELL_ID
android.permission.USE_COMPANION_TRANSPORTS
If your PR is related to an issue. Please end your PR test with the …
=> Update the list of permissions (up to API level 35)

techniques/ios/MASTG-TECH-0091.md
=> Fix continuity issue

techniques/ios/MASTG-TECH-0063.md
=> Update MASTG-TECH-0063.md fix Tool ID

tools/ios/MASTG-TOOL-0064.md
Just a quick update; the page was really outdated.
=> Update MASTG-TOOL-0064 Sileo (by @NVISOSecurity)

demos/ios/MASVS-RESILIENCE/MASTG-DEMO-0021/MASTG-DEMO-0021.md
=> Update MASTG-DEMO-0021 (fix output.asm ref in .md)

tools/android/MASTG-TOOL-0120.md
Small addition on ProxyDroid, including advantages and limitations.
=> Update ProxyDroid (by @NVISOSecurity)

docs/stylesheets/extra.css
Fixes #3102 
Borders are now consistent; tested in dark and light mode.
If new admonitions are used, it would require a small update to this code.
=> Fix admonition borders (by @NVISOSecurity)

weaknesses/MASVS-PLATFORM/MASWE-0058.md
=> Update MASWE-0058 Draft to add Ref

tests-beta/ios/MASVS-CODE/MASTG-TEST-0229.md
=> Update MASTG-TEST-0229 with info about False Positives

weaknesses/MASVS-STORAGE/MASWE-0001.md, weaknesses/MASVS-STORAGE/MASWE-0002.md, weaknesses/MASVS-STORAGE/MASWE-0003.md, weaknesses/MASVS-STORAGE/MASWE-0004.md
- Update all CWE IDs on MASWE elements of MASVS-STORAGE-2
=> Update CWE mapping on MASWE elements of MASVS-STORAGE-2.

weaknesses/MASVS-STORAGE/MASWE-0006.md, weaknesses/MASVS-STORAGE/MASWE-0007.md, weaknesses/MASVS-STORAGE/MASWE-0008.md
- Update all CWE IDs on MASWE elements of MASVS-STORAGE-1
=> Update CWE mapping on MASWE elements of MASVS-STORAGE-1.

weaknesses/MASVS-CRYPTO/MASWE-0009.md, weaknesses/MASVS-CRYPTO/MASWE-0010.md, weaknesses/MASVS-CRYPTO/MASWE-0011.md, weaknesses/MASVS-CRYPTO/MASWE-0012.md, weaknesses/MASVS-CRYPTO/MASWE-0014.md, weaknesses/MASVS-CRYPTO/MASWE-0015.md, weaknesses/MASVS-CRYPTO/MASWE-0016.md, weaknesses/MASVS-CRYPTO/MASWE-0017.md, weaknesses/MASVS-CRYPTO/MASWE-0018.md
- Update all CWE IDs on MASWE elements of MASVS-CRYPTO-2
=> Update CWE mapping on MASWE elements of MASVS-CRYPTO-2.

weaknesses/MASVS-CRYPTO/MASWE-0019.md, weaknesses/MASVS-CRYPTO/MASWE-0020.md, weaknesses/MASVS-CRYPTO/MASWE-0021.md, weaknesses/MASVS-CRYPTO/MASWE-0022.md, weaknesses/MASVS-CRYPTO/MASWE-0023.md, weaknesses/MASVS-CRYPTO/MASWE-0024.md, weaknesses/MASVS-CRYPTO/MASWE-0025.md, weaknesses/MASVS-CRYPTO/MASWE-0026.md, weaknesses/MASVS-CRYPTO/MASWE-0027.md
- Update all CWE IDs on MASWE elements of MASVS-CRYPTO-1
=> Update CWE mapping on MASWE elements of MASVS-CRYPTO-1

weaknesses/MASVS-NETWORK/MASWE-0047.md
- Update all CWE IDs on MASWE elements of MASVS-NETWORK-2
=> Update CWE mapping on MASWE elements of MASVS-NETWORK-2

tests-beta/android/MASVS-NETWORK/MASTG-TEST-0236.md, tests/android/MASVS-NETWORK/MASTG-TEST-0019.md, tests/ios/MASVS-NETWORK/MASTG-TEST-0065.md, tools/network/MASTG-TOOL-0079.md
ZAP left OWASP over a year ago.
- [na] Your contribution is written in the 2nd person (e.g. you)
- [na] Your contribution is written in an active present form for as much as possible.
=> Update ZAP mentions

tests/android/MASVS-STORAGE/MASTG-TEST-0001.md
=> [MASTG-TEST-0001] Add covered by MASTG-TEST-0201 and MASTG-TEST-0202

demos/android/MASVS-PLATFORM/MASTG-DEMO-0029/MASTG-DEMO-0029.md, demos/android/MASVS-PLATFORM/MASTG-DEMO-0030/MASTG-DEMO-0030.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0250.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0251.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0252.md, tests-beta/android/MASVS-PLATFORM/MASTG-TEST-0253.md
Introduce new drafts for demos and tests to address content access issues in Android WebViews.
=> [Drafts] Add demos and tests for WebView content access in Android

docs/hooks/maswe-beta-banner.py
Improve clarity and include specific identifiers in draft banners for tests and demos.
=> Refactor draft banners for tests and demos

Document/0x02c-Acknowledgements.md
=> Update 0x02c-Acknowledgements.md ( add clarification)

mkdocs.yml, techniques/ios/MASTG-TECH-0118.md, tests-beta/android/MASVS-CODE/MASTG-TEST-0222.md, tests-beta/android/MASVS-CODE/MASTG-TEST-0223.md, tests-beta/android/MASVS-NETWORK/MASTG-TEST-0244.md, tests/android/MASVS-NETWORK/MASTG-TEST-0019.md, tests/ios/MASVS-NETWORK/MASTG-TEST-0065.md, weaknesses/MASVS-NETWORK/MASWE-0047.md
Update various links to ensure they point to the correct files and sections.
=> Fix broken links

.gitignore, .vscode/launch.json, .vscode/settings.json, run_web.sh
- Add a directory for MASVS images to .gitignore
- Enhance the MkDocs server command with a dirty reload option
- Introduce a debug configuration for launching the current Python file in VSCode
- Customize editor colors for selection and find match backgrounds in VSCode settings.
=> Update development environment and settings

docs/contributing/6_Add_a_Crackme.md
=> Update 6_Add_a_Crackme.md - Fix links

.vscode/settings.json
Add custom colors for terminal match highlighting and borders to enhance visibility and user experience.
=> Add terminal color customizations to VSCode settings

Document/0x05d-Testing-Data-Storage.md
=> Fix naming error (password.txt to sensitive_info.txt)

Document/0x04a-Mobile-App-Taxonomy.md
Hi there, hope you're fine! 
This PR just removes a duplicated word at [Native Apps section](https://mas.owasp.org/MASTG/0x04a-Mobile-App-Taxonomy/#native-apps)
=> Remove the duplicated `these` word

Document/0x06b-iOS-Security-Testing.md
=> Update 0x06b-iOS-Security-Testing.md fix wrong tool ref

docs/hooks/create_dynamic_tables.py
Fixes the broken display of static/dynamic/network in the tests v2-beta table.
=> Fix styling in table for tests v2

.github/PULL_REQUEST_TEMPLATE.md
Enhance the pull request template by adding a dedicated description section and guidelines to improve clarity and compliance with contribution standards.
=> Update pull request template with description section and guidelines

demos/android/MASVS-NETWORK/MASTG-DEMO-0048/MASTG-DEMO-0048.md, demos/android/MASVS-NETWORK/MASTG-DEMO-0049/MASTG-DEMO-0049.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0041/MASTG-DEMO-0041.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0042/MASTG-DEMO-0042.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0043/MASTG-DEMO-0043.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0044/MASTG-DEMO-0044.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0045/MASTG-DEMO-0045.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0046/MASTG-DEMO-0046.md, demos/ios/MASVS-AUTH/MASTG-DEMO-0047/MASTG-DEMO-0047.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0266.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0267.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0268.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0269.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0270.md, tests-beta/ios/MASVS-AUTH/MASTG-TEST-0271.md
=> Add demo and test drafts

Document/0x08a-Testing-Tools.md, docs/contributing.md
First proposal for making tools section requirements more specific.
=> Update MASTG tools phrasing

docs/donate/how_to_donate.md, docs/donate/packages.md
=> fix table and buttons

mkdocs.yml
This PR disables the offline and privacy plugins.
=> Update mkdocs.yml - Disable new plugins

docs/hooks/create_dynamic_tables.py, docs/javascripts/datatables.js, docs/javascripts/filter_tests.js, mkdocs.yml, tests-beta/index.md
This pull request introduces a new filtering feature for the test table in the MASTG documentation. It adds a JavaScript-based filtering system, updates the documentation to explain the feature, and integrates the necessary script into the build configuration.
* **JavaScript Implementation**: Added `filter_tests.js` to enable dynamic filtering of the test table by status, platform, and compliance profile. The script includes functionality for grouping filters, applying multiple filters simultaneously, and resetting filters with a "Clear All Filters" button. Deprecated tests are hidden by default unless explicitly shown.
* **Configuration Update**: Included the new `filter_tests.js` script in the `extra_javascript` section of `mkdocs.yml` to ensure it is loaded during documentation …
=> Add Filters for Tests

docs/javascripts/datatables.js, docs/javascripts/filter_tests.js
Update the table sorting so that you can now again search for IDs and titles.
=> Refactor table search

Document/0x04a-Mobile-App-Taxonomy.md
It was a bit outdated and changed the taxonomy itself to be more inline with current industry wording.
=> Update taxonomy section

techniques/ios/MASTG-TECH-0137.md, techniques/ios/MASTG-TECH-0138.md, tools/ios/MASTG-TOOL-0135.md, tools/ios/MASTG-TOOL-0136.md
Closes #3343
This PR adds PlistBuddy and plistlib.
=> Adds PlistBuddy and plistlib

Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md
Remove references to commercial products as not in line with tool contribution guidelines.
=> Remove references

demos/android/MASVS-STORAGE/MASTG-DEMO-0002/output.txt, demos/android/MASVS-STORAGE/MASTG-DEMO-0002/script.js, demos/ios/MASVS-AUTH/MASTG-DEMO-0044/output.txt, demos/ios/MASVS-AUTH/MASTG-DEMO-0044/script.js
Fixes current demos as indicated in https://mas.owasp.org/MASTG/tools/generic/MASTG-TOOL-0031/#frida-17
=> Fix Demos for Frida 17

Dockerfile, README.md, docs/contributing/1_How_Can_You_Contribute.md, docs/contributing/2_Getting_Started.md, docs/contributing/3_PRs_and_Reviews.md, docs/contributing/5_Style_Guide.md, docs/contributing/7_Run_the_Website.md
Include the MASWE repository in the Dockerfile and update documentation to reflect the requirement of cloning both MASVS and MASWE alongside MASTG for the website build. Adjust instructions for clarity on repository setup.
=> Update README to align with other repos and Improve Contribution Docs

Document/0x02c-Acknowledgements.md
=> Fix small typo in 0x02c-Acknowledgements.md

Document/index.md
Change navigation links in index.md to use relative paths for improved link management.
=> Update navigation links to use relative paths

tools/ios/MASTG-TOOL-0043.md
Added class-dump dockerized version to MASTG-TOOL-0043 - which is a version I personally built.
=> Added class-dump dockerized version to MASTG-TOOL-0043

techniques/android/MASTG-TECH-0112.md, techniques/android/MASTG-TECH-0116.md, techniques/android/MASTG-TECH-0117.md, techniques/android/MASTG-TECH-0128.md, techniques/android/MASTG-TECH-0130.md, techniques/android/MASTG-TECH-0131.md, techniques/android/MASTG-TECH-0140.md
This PR relates to #3473
Fix punctuation and some grammar mistakes in android folder: TECH 112-140
=> Fix punctuation and some grammar mistakes in android folder: TECH 112-140

demos/android/MASVS-CODE/MASTG-DEMO-0025/output.txt, demos/android/MASVS-CODE/MASTG-DEMO-0025/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0007/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0008/output.txt, demos/android/MASVS-CRYPTO/MASTG-DEMO-0008/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0012/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0017/output.txt, demos/android/MASVS-CRYPTO/MASTG-DEMO-0017/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0022/run.sh, demos/android/MASVS-CRYPTO/MASTG-DEMO-0023/run.sh, demos/android/MASVS-NETWORK/MASTG-DEMO-0054/run.sh, demos/android/MASVS-NETWORK/MASTG-DEMO-0055/run.sh, demos/android/MASVS-NETWORK/MASTG-DEMO-0056/run.sh, demos/android/MASVS-NETWORK/MASTG-DEMO-0057/run.sh, demos/android/MASVS-PLATFORM/MASTG-DEMO-0032/run.sh, demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/output.txt, demos/android/MASVS-RESILIENCE/MASTG-DEMO-0028/run.sh, demos/android/MASVS-RESILIENCE/MASTG-DEMO-0039/run.sh, demos/android/MASVS-STORAGE/MASTG-DEMO-0003/output.txt, demos/android/MASVS-STORAGE/MASTG-DEMO-0003/output2.txt, demos/android/MASVS-STORAGE/MASTG-DEMO-0003/run.sh, demos/android/MASVS-STORAGE/MASTG-DEMO-0004/output.txt, demos/android/MASVS-STORAGE/MASTG-DEMO-0004/run.sh, demos/android/MASVS-STORAGE/MASTG-DEMO-0005/output.txt, demos/android/MASVS-STORAGE/MASTG-DEMO-0005/run.sh
Align all semgrep commands and their exports
=> [Housekeeping] Align all semgrep commands and their exports
